### ISSUE TITLE
Problem with contact serial port

### ISSUE THREAD

**Issue by MigSOBR** [dcs-bios/dcs-bios#100]
and the end comes this:
C:\Users\aleks\Desktop\dcs-bios-v0.5.0>socat\socat -v UDP4-RECV:5010,ip-add-membership=239.255.50.10:127.0.0.1,reuseaddr!!udp-sendto:localhost:7778 /dev/ttyS6
      0 [main] socat 3504 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com

ps i use windows 10

MigSOBR

**Comment by jboecker** [comment]
That warning message is normal on Windows 10, but everything still works. You can ignore it.

What steps did you take, what did you expect to happen and what happened (or didn't happen) instead?
Which version of DCS are you using? Are you running any other software that uses Export.lua such as Helios, TacView, etc.?

Any errors in your dcs.log?

**Comment by MigSOBR** [comment]
ups i just need to start dcs and than the cmd haha sorry but thanks for the info with win 10

MigSOBR
