### ISSUE TITLE
Adding an Export Module for Your Aircraft

### ISSUE THREAD

**Issue by SimoneRighitto** [dcs-bios/dcs-bios#102]
Hello,

First of all I would like to say a big thanks to all developers of dcs-bios ! It's a really well done project and a great help for the cockpit builders !

Up to my question now:

I have started looking into dcs-bios usage and development in order to add support for a new aircraft.  I have read the dcs-bios manual and developer guide but I have some difficulties understanding some details:

In the given example 
defineToggleSwitch("BATTERY_POWER", 1, 3006, 246, "Electrical Power Panel", "Battery Power")  [from http://dcs-bios.a10c.de/docs/v0.5.0/developerguide.html ]
I have difficulties to understand how it was possible to find the corrects value needed. I have looked at the function signature [from dcs-bios/Util.lua] : 

function BIOS.util.defineToggleSwitch(msg, device_id, command, arg_number, category, description)

But I'm not able to understand where the values come from. Can someone please give me a clear explanation like:
msg --> found in dcs file xxx.lua
device_id --> proper id for dcs-bios
arg_number --> found in dcs file yyy.lua
etc...

This will help me understanding how it is possible to match the dcs clickable or not controls with the dcs-bios aircraft.lua file.

I am at the beginning of my dcs-bios usage / dev , so please excuse me if the question look simple or confused ;)

Don't hesitate to ask me for more details about the problem.

Have a nice day ;)

Simone

**Comment by jboecker** [comment]
In general, you will find the relevant files in `C:\Program Files\Eagle Dynamics\DCS World\mods\YOUR_AIRCRAFT\Cockpit\Scripts`. Interactive elements are defined in `clickabledata.lua`, while indicator lights and gauges are found in `mainpanel_init.lua`.

The message (`BATTERY_POWER`) is an arbitrary, short string(keep it less than 20 characters) that identifies the control for DCS-BIOS. For example, when you define that switch in your Arduino sketch and turn it on, the Arduino would then send `BATTERY_POWER 1\n` to DCS-BIOS.

An argument number identifies a "draw argument" for the cockpit 3D model. Every animation in the cockpit has one and DCS-BIOS can read them. By looking at the draw argument for e.g. a toggle switch, we can tell the current switch position.

The device ID (1) and command (3006) are needed to give commands to DCS from Export.lua. When DCS-BIOS receives `BATTERY_POWER 1\n` in the above example, it will end up executing `GetDevice(1):performClickableAction(3006, 1.0)` from Export.lua.

For more information about argument numbers, device IDs and commands refer to the [Beginner's Guide to DCS World Aircraft Mods](https://forums.eagle.ru/showthread.php?t=116901) in the `Mods and Apps > How To` section on the ED forums.

You also might want to check out the ED Model Viewer, which lets you load the 3D model of the cockpit and manipulate the various cockpit arguments to see what those animations do.

**Comment by SimoneRighitto** [comment]
Good morning,

Thank you very much for the reply and for the useful information ;)

In the next day I'll jump into the code and documentation and everything will become more clear .

I have found another project that could help me (or other entusiast that want to start playing with dcs and cookpit building) : the Ikarus project - https://github.com/H-J-P/Ikarus

Bye Bye
