### ISSUE TITLE
inaccurate instructions

### ISSUE THREAD

**Issue by wiscodin** [dcs-bios/dcs-bios#103]
In the DCS-BIOS user guide it says, "Click File → Examples → DcsBios → TemplateSketch to open the template program that comes with the DCS-BIOS Arduino library."

This so called "templatesketch" simply isn't there and all the other preloaded sketches either don't have enough information to commuincate with DCS or when I try to upload them to my board they're full of error messages that I don't know how to solve.  
Please help.  I'm building a simulator of the UH-1H in DCS and I need the arduino to properly work the radio controls.

**Comment by jboecker** [comment]
Looks like I missed a place in the documentation when I added RS-485 support and changed the names of the template sketches.

Use the `IRQSerial` example.

The `IRQSerial`, `DefaultSerial` and `MasterCaution` examples have everything that is needed to communicate with DCS from the Arduino side (the other two are meant for RS-485 buses).
