### ISSUE TITLE
TACAN

### ISSUE THREAD

**Issue by Killroy21** [dcs-bios/dcs-bios#106]
Hi

Complete newbie on dcs-dios/Arduino program languages and my English is not the best but hers my problem. 

Trying to get TACAN Channel to work whit a 0,96" oled screen.
The screen is working whit this sketch it prints 0 5 0 X

#include "U8glib.h"

U8GLIB_SSD1306_128X64 oled(U8G_I2C_OPT_NONE);

char line1[] = "0 5 0 X";
//char line2[] = "";
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  
  oled.firstPage();
    do{
      draw();
    } while(oled.nextPage());

}
void draw(void) {

 // put your main code here, to run repeatedly:
  oled.setFont(u8g_font_helvR24);
  int lineHight = oled.getFontAscent()-oled.getFontDescent();

  int line1x = (oled.getWidth()-oled.getStrWidth(line1)) / 2;
  //int line2x = (oled.getWidth()-oled.getStrWidth(line2)) / 2;

 oled.drawStr(line1x, lineHight * 1.5, line1);
  //oled.drawStr(line2x, lineHight * 3, line2);
  }

but I cant get it to work with TACAN it only prints number 1 on the screen. 

What am i doing wrong in the sketch?
 
#include "U8glib.h"
#define DCSBIOS_IRQ_SERIAL
#include "DcsBios.h"
U8GLIB_SSD1306_128X64 oled(U8G_I2C_OPT_NONE);
char tac; 

//Right Channel SelectorA-10C/TACAN_1
DcsBios::RotaryEncoder tacan1("TACAN_1", "DEC", "INC", 13, 12);
//Left Channel SelectorA-10C/TACAN_10
DcsBios::RotaryEncoder tacan10("TACAN_10", "DEC", "INC", 5, 6);
//TACAN Mode DialA-10C/TACAN_MODE
const byte tacanModePins[5] = {11, 10, 9, 8, 7};
DcsBios::SwitchMultiPos tacanMode("TACAN_MODE", tacanModePins, 5);
//TACAN Test Indicator LightA-10C/TACAN_TEST
DcsBios::LED tacanTest(0x10da, 0x0400, 4);
//TACAN Test ButtonA-10C/TACAN_TEST_BTN
DcsBios::Switch2Pos tacanTestBtn("TACAN_TEST_BTN", 3);
//TACAN Channel X/Y ToggleA-10C/TACAN_XY
DcsBios::ActionButton tacanXy("TACAN_XY", "TOGGLE", 15);

//TACAN ChannelA-10C/TACAN_CHANNEL

void onTacanChannelChange(char* newValue) {
  
  tac = newValue; 
  
}

DcsBios::StringBuffer<4> tacanChannelBuffer(0x1162, onTacanChannelChange);

void setup() {
  DcsBios::setup();
}

void loop() {
    oled.firstPage();
    do{
      draw();
    } while(oled.nextPage());
    delay(20);
    onTacanChannelChange;
    DcsBios::loop();
}

void draw(void) {
  oled.setFont(u8g_font_helvR24);
  oled.setPrintPos(50, 50);
  oled.print(tac);
 }

Grateful for all help I can get.
Micke

**Comment by jboecker** [comment]
When the TACAN channel changes, `onTacanChannelChange` will be called. The parameter `char* newValue` is a pointer to the beginning of a piece of memory that contains the new text. In other words, `newValue` contains the *memory address* of the first character of the new channel string.

The assignment `tac = newValue` copies this address to the variable `tac`, which is of type `char`. So you are interpreting a memory address as a character value, which makes no sense in most cases but the compiler lets you do that anyway.

The compiler can help you catch errors like this by emitting a "compiler warning". You can turn on compiler warnings in the Arduino IDE's Preferences (FIle -> Preferences). When setting it to 'Default' or higher, I get the following warning in orange text when compiling your code:
````C:\...\issue106\issue106.ino: In function 'void onTacanChannelChange(char*)':

C:\...\issue106\issue106.ino:25:5: warning: invalid conversion from 'char*' to 'char' [-fpermissive]

 tac = newValue;

     ^
````

If you change the type of the `tac` variable in line 5 from `char` to `char*`, it should work.

You could also get rid of the global `tac` variable and put all of your drawing code into the `onTacanChannelChange` function. This has the advantage that the display gets updated only when something has changed. This reduces the overall workload of the Arduino and increases its response time to other things, such as reacting to inputs on the button and rotary encoders.

**Comment by Killroy21** [comment]
Thanks for the replay. [😊]

________________________________
Från: jboecker <notifications@github.com>
Skickat: den 1 maj 2017 01:15
Till: dcs-bios/dcs-bios
Kopia: Killroy21; Author
Ämne: Re: [dcs-bios/dcs-bios] TACAN (#106)


When the TACAN channel changes, onTacanChannelChange will be called. The parameter char* newValue is a pointer to the beginning of a piece of memory that contains the new text. In other words, newValue contains the memory address of the first character of the new channel string.

The assignment tac = newValue copies this address to the variable tac, which is of type char. So you are interpreting a memory address as a character value, which makes no sense in most cases but the compiler lets you do that anyway.

The compiler can help you catch errors like this by emitting a "compiler warning". You can turn on compiler warnings in the Arduino IDE's Preferences (FIle -> Preferences). When setting it to 'Default' or higher, I get the following warning in orange text when compiling your code:


C:\...\issue106\issue106.ino:25:5: warning: invalid conversion from 'char*' to 'char' [-fpermissive]

 tac = newValue;

     ^


If you change the type of the tac variable in line 5 from char to char*, it should work.

You could also get rid of the global tac variable and put all of your drawing code into the onTacanChannelChange function. This has the advantage that the display gets updated only when something has changed. This reduces the overall workload of the Arduino and increases its response time to other things, such as reacting to inputs on the button and rotary encoders.
