### ISSUE TITLE
 communication problem between arduino and socat ?

### ISSUE THREAD

**Issue by ShuraDE** [dcs-bios/dcs-bios#118]
Hi,

i have a communication problem between arduino and dcs.

Building [master caution sample](https://github.com/dcs-bios/dcs-bios/blob/master/Scripts/DCS-BIOS/doc/userguide.adoc#the-mastercaution-example-sketch).

After execute serial connect script and start a dcs mission the command window prints much data.
[Chrome Extension](http://www.checksix-forums.com/viewforum.php?f=286&sid=c0717733d6f7ba9342758baa4876f924) show all data and is functional.

Breadboard is dead.... reset button didnt work and no led is blinking after raising a master caution.
RX blinks high frequently, TX everytime i push and release pushbutton for caution reset button.
Tried/checked:
* two way switch instead a [pushbutton](https://cdn.sparkfun.com//assets/parts/9/0/00097-03-L.jpg) same result
* old(?)  from example and new(?) from documentation
> DcsBios::LED masterCaution(0x108e, 0x0008, 13);
> DcsBios::LED masterCaution(0x1012, 0x0800, 13);
* Firewall is checked twice,  socat and dcs are complete open.
* TCP and UDP also with same result.
* disable other mods (SRS, tacview, tacnoworld)
* first boards was china versions from uno, now a original mega 2560
* IRQ and default serial 
* other [connect script](https://forums.eagle.ru/member.php?u=95995)

If i just press the button, the commandline shows:
> < 2017/10/29 10:33:32.514784  length=8 from=0 to=7
.@?.>.P.< 2017/10/29 10:33:32.699129  length=8 from=8 to=15
.@?.~^..

Push often results in [pastebin link](https://pastebin.com/qe9bJZYP)

dcs-bios.log is empty
[dcs.log](https://pastebin.com/sVVA3fQT)

Anyone a clue ?  Hangs since a week :-/

**Comment by ShuraDE** [comment]
Is it possible that the troubles causes by my charset ?
If i compare this [screenshot](https://cloud.githubusercontent.com/assets/18270037/16710245/1e56b926-4628-11e6-99f1-a87a00b9cbfd.png) from #93 with my output there are different message generated. His msg is plaintext and my one looked confusing.

**Comment by jboecker** [comment]
v0.7.1 should fix this.

**Comment by ShuraDE** [comment]
no problems anymore, thank you =)
