### ISSUE TITLE
IFF integration observations

### ISSUE THREAD

**Issue by 132ndHansolo** [dcs-bios/dcs-bios#127]
**1. 'Reply' and 'Test' light**
The actual light for the Reply and Test aren’t exported. Only the push to test status is. Looking at the DCS-BIOS code it may just need following added;

defineIndicatorLight("IFF_REPLY", 798, "IFF", "REPLY")
defineIndicatorLight("IFF_REPLY", 799, "IFF", "TEST")

**2.  ‘Mode 4 Audio-Out-Light'**
The ‘Mode 4 Audio-Out-Light' on the A-10C IFF seems to move less than it should. When toggling the panel SOCAT does report 0-1-2 for the positions however in-game the toggle doesn’t move sufficient. It’s like the command is insuffient, 1:24 (https://youtu.be/XPcGNR6pSHc?t=1m22s). 
When toggling directly in game the toggle moves fully into all three positions.

**Comment by WarLord211** [comment]
Updated and fixed
