### ISSUE TITLE
Hud-Only view = no CDU export

### ISSUE THREAD

**Issue by talbotmcinnis** [dcs-bios/dcs-bios#133]
Awesome work on this.  Simply amazing project.

I have pygame consuming DCS-BIOS data via UDP from another PC.  Specifically CDU data but I don't think that matters.

When in-pit default F1 view, it works like a charm.  When I use hud-only view, the data export stops.  Any ideas how I can keep this data stream continuing while in HUD-only view?

**Comment by BenTrem** [comment]
On 5/9/2018 9:03 PM, talbotmcinnis wrote:
>
> Awesome work on this. Simply amazing project.
>
/Hear, hear!/
>
> I have pygame consuming DCS-BIOS data via UDP from another PC.
>
You really perked me with this.
My venerable Toshiba ToughBook is sitting on a shelf near me. Because 
this tiny perfect unit has a touch screen I've always wondered how I 
might harness that input capability in this role.

--Dawks [PIR]

**Comment by talbotmcinnis** [comment]
Checkout by brief youtube vid on the subject.  Source code is on git.  

https://youtu.be/bybeSSa3HRM

Talbot McInnis
Senior Software Architect
787 Networks Inc
Home of Bowling Music Network & controlPLAY.
Phone: 1-866-684-8324 ext. 228
Fax: 1-866-295-4281
talbot.mcinnis@787networks.com

**Comment by BenTrem** [comment]
On 5/9/2018 9:50 PM, talbotmcinnis wrote:
> Checkout by brief youtube vid on the subject. Source code is on git.
> https://youtu.be/bybeSSa3HRM
Ace. Solid copy.
I'm sure mine is an edge case (to get pair of Cougar MFDs online using 
venerable ToughBook!) but I'm sure ever more touch-screen devices will 
become present.

> Talbot McInnis
--ben
> Senior Software Architect

once was jump-trained SigInt

> Home of Bowling Music Network & controlPLAY.
I bought Christmas presents for my 4 daughters by playing music on 
Halifax streets mid-winter
;-)

^5

**Comment by talbotmcinnis** [comment]
This is working just fine, both DCS-bios and my CDU export.  I do think some things export differently in hud-only view (TACAN freq for example, but it does eventually sync it just takes a while.  Easy to pop back into cockpit view when tuning, so I think this is a non-issue.
