### ISSUE TITLE
F18

### ISSUE THREAD

**Issue by Flyingspanner72** [dcs-bios/dcs-bios#134]
Hi Guys,

Is there anyone with the skills enough to make a set for the F18 which has been released?

I hope so, wish I had the tech knowledge to do it myself.

Thanks

**Comment by 132ndHansolo** [comment]
Check ED forums. AndrewW has been so kind to dedicate time to try and make it for the Hornet. https://forums.eagle.ru/showthread.php?t=209941

Make sure to give him some thanks for his hard work

**Comment by Flyingspanner72** [comment]
Thanks for the info.

Great stuff, need to know how to program DCS Bios now!!!
