### ISSUE TITLE
DCS BIOS and L-39

### ISSUE THREAD

**Issue by Mabo72** [dcs-bios/dcs-bios#135]
Hi, 
if it works with you?

**Comment by Flyingspanner72** [comment]
Hi Mabo,

seriously thanks for the info. now need to work out how to implement it.

If you recieve this message please respond as I may have a few questions.

Thanks
John

**Comment by Mabo72** [comment]
Hi,

Every other moduls works under Dcs bios. Only L-39 don't.


czw., 14 cze 2018, 13:09 użytkownik Flyingspanner72 <
notifications@github.com> napisał:

> Hi Mabo,
>
> seriously thanks for the info. now need to work out how to implement it.
>
> If you recieve this message please respond as I may have a few questions.
>
> Thanks
> John
>

**Comment by bjanders** [comment]
I'm not sure if I understand the question, but I have got the L-39 module to work. Note however that out-of-the-box it only works with the L-39ZA variant and not L-39C. To get L-39C also to work, all you have to do is change a line in Scripts\DCS-BIOS\lib\L-39ZA.lua. Change the following line:

    BIOS.protocol.setExportModuleAircrafts({"L-39ZA"})

to:

    BIOS.protocol.setExportModuleAircrafts({"L-39C", "L-39ZA"})

And it will work with both variants. 

There are quite many controls that haven't been implemented though. I might add more at some point.
