### ISSUE TITLE
DCS-BIOS: CDU- Display (Font issue)

### ISSUE THREAD

**Issue by Ravenor712** [dcs-bios/dcs-bios#137]
Hi there,

my name is Tobias and a few weeks ago i started to build the first instruments for my homecockpit. Personaly, i have absolute no experience with programming, but after finding your DCS-BIOS my learning curve has gone very high. 

![imag0208](https://user-images.githubusercontent.com/40805078/42294011-4a266636-7fde-11e8-885d-aa19739b9f0e.jpg)

And so i was able to build my first panel, the CMSP (see attachement). A big thanks to you [FS]Ian for this great tool.

_______________________________________________________________________________________________________________
Hardware:
- Arduino DUE
- Arduino TFT Shield **( ILI9488 )**
- 3.5" TFT Display

Software:
- UTFT Library

After the CMSP i started to build the CDU, especialy the display and that brings mit to two issues:

**1.)** IRQ serial does not function with Arduino DUE: I am not able to upload a IRQ serial based sketch to the Arduino DUE, i must use the DefaultSerial

**2.)** UTFT-Fonts: That´s the biggest issue, i have strange values on the display when i run it in DCS World.

![imag0210](https://user-images.githubusercontent.com/40805078/42294319-4453346c-7fe0-11e8-8b07-0b7857f7d254.jpg)

After reading this [issue with a link to a code site](https://github.com/dcs-bios/dcs-bios/commit/515bb3c982c28e7bb011eb83f64fbe77abdc31e5), i know that i have to find out how i can chance the fonts.

I will be very helpfull for me when someone can descripe me step by step what i have to do to change, example the "degree" value, in the UTFT-Fonts. Actual i have no idea where i should start...

Best greetings and a big thanks in advance, Tobi.

**Comment by ArjanJGrootenboer** [comment]
Hi Ravenor,

I have made a new font for the UTFT lib, please look at forums.eagle.ru, DCS-BIOS TFT font issue.
