### ISSUE TITLE
how to install DCS bios

### ISSUE THREAD

**Issue by tonygard** [dcs-bios/dcs-bios#138]
i would realy like to know where dcs-bios goes

**Comment by jdahlblom** [comment]
Hold on, I'll get someone to post screenshots for you.

**Comment by tonygard** [comment]
cool thanks it is really complicated to set up😥

**Comment by tonygard** [comment]
preferably from download to install and how to use it to setup saitek
panels the video i have watched are really confusing

**Comment by tonygard** [comment]
😥 haven't heard back from you

**Comment by jdahlblom** [comment]
OK, I've asked pdmarsh to help out, he is in another time zone though.
Sorry, I am without my dev PC so I can't assist with screenshots etc.
You can also post here https://forums.eagle.ru/showthread.php?t=137670&page=89
That is where we handle support, I noticed you want to use DCSFlightpanels so that is prolly the best place to ask questions.

**Comment by tonygard** [comment]
Ok 
Thanks for getting back to me
Do you know any one on that forum I can get help from 
I am going NUTS trying to work out how to install the DCS-BIOS and where to install it to and how to use it with DCSFlightpanels x64_2.6.3 and DCSFlightPanels-master
tony

Sent from Mail for Windows 10

**Comment by jdahlblom** [comment]
Post in the thread, there are several ppl that can help. :)

**Comment by jdahlblom** [comment]
![gh2](https://user-images.githubusercontent.com/10453261/46355418-71540e80-c669-11e8-95d3-488d33ae29bb.jpg)
![gh1](https://user-images.githubusercontent.com/10453261/46355419-71540e80-c669-11e8-995c-91d6660bffa1.jpg)
![gh3](https://user-images.githubusercontent.com/10453261/46355420-71540e80-c669-11e8-8032-6ee916529252.jpg)

**Comment by tonygard** [comment]
Hi
thanks for that but as i said i am a TOTAL ludite so all that script stuff
is way above my head
iam an old man and cant undersnd all the code stuff and where everthing is
suppsed to go
it would be nice if there was some wat of geetins aprifile or something so
i cand just install it and away i go
i have been usin xplane 11 a lot and i use xsatekpanes
itwould be nice if dcs world had something like that where i dont have to
be a rocket scientist😥
i will have a go at what youve sent me (but i dont like my chances)
thanks again for taking the time to help
tony

**Comment by tonygard** [comment]
also is  dcs -bios ONLY for arduino and can it be used for siatek panels

**Comment by jdahlblom** [comment]
DCS-BIOS is not only for Arduino. By using DCS-BIOS with DCSFP you get more or less access to the whole cockpit. You can e.g. read all kinds of values and you have more control over the switch bindings. Almost forgot, for the radio panel to work you also need it.

**Comment by tonygard** [comment]
Thank,I tried to follow what you sent but my file structure looks nothing like yours I still don’t understand where the dcs-bios-v0.7.1
Is supposed to go and DCSFLightpanel -master and DCSFlightpanels_x64_2.6.3 
tony
Sent from Mail for Windows 10

**Comment by tonygard** [comment]
and how do you find the "SAVED GAMES" foldder

**Comment by tonygard** [comment]
i just downloaded instructions for installing the dcs -bios ad it is all
for arduino there is nothing abouthow to get to use with saitek panels😥😭

**Comment by jdahlblom** [comment]
You find saved games by pasting this line into you file explorer 
`C:\Users\<username>\Saved Games`
Just change the <username> to your username.

**Comment by jdahlblom** [comment]
On how to use DCS-BIOS with DCSFP pdmarsh made a video : https://youtu.be/1CnmIdzqOJs
Also on key emulation : https://youtu.be/mgm0JfldgYs

**Comment by tonygard** [comment]
ive watched them but i STILL dont get it how do you use it in conjuction
with DCS-bios

**Comment by jdahlblom** [comment]
Perhaps you can leave DCS-BIOS for now then? Perhaps just focus on key emulation in the beginning?

**Comment by tonygard** [comment]
yes i think so lets keep it simple cause i am simple
i have tried using the saitek panel config tool ,managed to get on switch
to work but i cant get the bip panel light to light up when i press
"say"the landing light switch
and how does DCS know you have saitek panels

**Comment by tonygard** [comment]
how come the dont show up in the controls in dcs like all the other devices

**Comment by jdahlblom** [comment]
The Saitek panels aren't that kind of devices like joysticks and such (HID). Therefore I made this software.
Look at the screenshot, there you see the menu for the BIP. It is also covered in the tutorial videos. 
![gh4](https://user-images.githubusercontent.com/10453261/46363568-0829c680-c67c-11e8-80b5-fef495886707.jpg)

**Comment by tonygard** [comment]
Yes I have spent countless hours on it but it is way to complicate for my tiny brain I am not a well educated man I find it very very difficult to follow 
Every one makes it look easy but to me it is totally confounding and frustrating , i just wish everything was plug and play let all the geniuses to the hard stuff and let idiots like me just plug it in an it just works

**Comment by tonygard** [comment]
Is there any way you could send me a pre  configured  script that I could 
Put somewhere so my panels will work I have a saitek radio ,autopilot,switch panel and Bip panel
I would be more than happy to pay for your time and effort🙏💵

**Comment by jdahlblom** [comment]
I can't do it, sorry. It does work like that, DCS-BIOS needs to be correct etc etc. You don't have anyone that can help you? Don't know what else there is besides someone you know that could help.

**Comment by tonygard** [comment]
Nah tried everything no help any where I live in Tasmania and there is no one close I know 
I will have to plug on on my own ( will probably end up chuckin the whole thing out the window)
Thanks any way

Sent from Mail for Windows 10

**Comment by jdahlblom** [comment]
Prefer Team Viewer.
Email me at jerker.dahlblom@gmail.com

**Comment by aymeen1** [comment]
hi
im new in dcs bios. im trying to build my f-5e cockpit. the following file f-5e.lua ,the f-5e.json and f-5e.jsonp ., i dont find them in the net .

**Comment by jdahlblom** [comment]
Hi,
Download DCS-BIOS from here. F-5E lua & json included.
https://github.com/DCSFlightpanels/dcs-bios/releases/tag/0.7.13

**Comment by tonygard** [comment]
HI where do I put it (in the saved game foder) ?

Sent from Mail for Windows 10

**Comment by jdahlblom** [comment]
Yes, unzip and place them there. Look at the screenshot earlier in the thread for directory structure.

**Comment by tonygard** [comment]
Sorry I forget how to get to the specific thread

Sent from Mail for Windows 10

**Comment by jdahlblom** [comment]
Sorry Tony, helping out an other person trying to get DCS-BIOS installed, you get the emails too.

**Comment by tonygard** [comment]
Ok I will wing it

Sent from Mail for Windows 10

**Comment by aymeen1** [comment]
hi
thank you jerker
