### ISSUE TITLE
F-5E - Sight Reticle Depression Knob - not working properly

### ISSUE THREAD

**Issue by rglasinovic** [dcs-bios/dcs-bios#143]
Hello
I have an issue with this control. I have tested two version of this command: digitally with Rotary Encoder and analogical with Potenciometer. Both produces the same result. It only increment the deppresion value of the sight in a very big step, regardeless the rotarion direction. I mean a CW or CCW turn direction always increment deprresion value.

Salute
Gavilan

**Comment by WarLord211** [comment]
i check it

**Comment by rglasinovic** [comment]
Thanks Warlod.
Rotary Encoder works great!
Potentiometer is working like before (only increasing).
I solved this issue for me.
Great!
