### ISSUE TITLE
F-5E - UHF Radio Volume Knob compiler error

### ISSUE THREAD

**Issue by rglasinovic** [dcs-bios/dcs-bios#144]
Hello
I have tried to bind a potentiometer to UFH radio volume control. I have use this command in its straight forward way (replacing the PIN obviously)

DcsBios::Potentiometer uhfVol("UHF_VOL", PIN); 

But when I compile it, arduino IDE throws an error.

Is it possible to check this?

Thanks.

Salute
Gavilan

**Comment by WarLord211** [comment]
hm. i dont know how thes arduino thing works.
but i have checked it an it should work.
please test it.
i made a new release with the updated file.
it good to load a mission with any plane and jump in the cockpit to force DCS_BIOS to made the json files new (needed for ref page).

update is in flightpanel DCS BIOS

**Comment by rglasinovic** [comment]
Thanks again Warlord
Now it works great!
