### ISSUE TITLE
DCS Su-27 question

### ISSUE THREAD

**Issue by Teofly** [dcs-bios/dcs-bios#148]
Hi,

I would like to say thanks to all developers of Dcs-Bios ! It's a really well done software and a great help for building a cockpit.
I start my project for a full 6-dof motion simulator using DCS,
I already find a solution to connect inputs to the aircraft like switches and buttons (with a HID interface from leobodnar) I have some problems to connect outputs like leds... i install dcs-bios and configure arduino board easy but when i try to let it work with Su-27 i cannot find documentation! Is it possible to connect dcs-bios with su-27 aircraft? where can i find documentation to paste on a sketch? Could i find the strings for myself? how?

Thanks in advance for your reply and

Blue Skies,
Matteo.

**Comment by WarLord211** [comment]
For fc3 planes only heading, alttitude and speed readablevia bios. Sadly nothing else, even when you know the right arguments.
i have tryed it.
