### ISSUE TITLE
Any work in progress for C-101CC? I'd like to learn and colaborate

### ISSUE THREAD

**Issue by rglasinovic** [dcs-bios/dcs-bios#149]
Hi
Has somebady alredady started on this? I'd like to learn how to create a def file.
I know that current state of C-101CC is based on toggle commands instead of states. Is it an issue?
Salute
Gavilan

**Comment by WarLord211** [comment]
i have the files but not startet yet. not even look over it.

**Comment by rglasinovic** [comment]
Any suggestion for me about how to start with? I have already read DCS BIOS documentation and still don't know how to catch data from DCS.
I have read that there are some functions that accepts parameters which are not documented yet.
Warlord, do you have any internal comm channel we can use for this?

**Comment by WarLord211** [comment]
there is a discord server for DCS_Bios flightpanels,....

https://discord.gg/5svGwKX

i made 2 bios files (F5 and Mig15) there was always copy/paste try and error and look how its in the a-10 going ;P

i had a quick look in the C-101 files and it sems like this is a challange one.

anyway lets move to discord :)
