### ISSUE TITLE
TF-51D support

### ISSUE THREAD

**Issue by jboecker** [dcs-bios/dcs-bios#15]
After v0.1.0, it might be a good idea to add TF-51D support so we have an example module that anyone can try. This could help people who want to add support for an existing module, but don't have one of the modules that are already supported.

For the TF-51D, we should also think about splitting its allocation into two memory maps: one for the controls it shares with the P-51, one for the TF-51D specific ones. This would require small additions to the core.

**Comment by toxaq** [comment]
I'm working on a P-51 module. Totally agree that a commonly available module that a bulletproof example could work with would be great. I don't have an A10 so all the examples took a long time to get my head around!

**Comment by toxaq** [comment]
Linking to #68 as I'll document my progress there.

**Comment by WarLord211** [comment]
T-51 in P-51 profile integraded
