### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by metmets** [dcs-bios/dcs-bios#153]
Hello,

The website http://dcs-bios.a10c.de/ appears to be down.

All the best.

**Comment by WarLord211** [comment]
looks down from here too.
But you can find parts from the side under \DCS-BIOS\doc.
:)

**Comment by metmets** [comment]
Do you have any idea when it might be back up again? 

I need that list where you could see the codes for different buttons and lights so that I can buy the lights and switches I need for my cockpit.

**Comment by WarLord211** [comment]
Sorry i dont know.

**Comment by ericedelman-gh** [comment]
> I need that list where you could see the codes for different buttons and lights so that I can buy the lights and switches I need for my cockpit.

You can download the files here from Github and open Scripts/DCS-BIOS/doc/control-reference.html in your local browser.

**Comment by WarLord211** [comment]
So i have checked some things
everything what was on the page is in the doc files. User guide and developers guide
checked with this copy from the page:
https://web.archive.org/web/20181107213043/http://dcs-bios.a10c.de/
