### ISSUE TITLE
DCS F-14 question

### ISSUE THREAD

**Issue by Mabo72** [dcs-bios/dcs-bios#156]
Do you plan to add support for 7-segment displays? (VHF, UHF, UHF1, UHF2)?

**Comment by Mabo72** [comment]
Do you plan to add support for 7-segment displays? (UHF, VHF, UHF1, UHF2 )?

**Comment by WarLord211** [comment]
support in which way?

**Comment by Mabo72** [comment]
Yes, like example TACAN in A-10C:

void onTacanChannelChange(char* newValue) {
    /* your code here */
}
DcsBios::StringBuffer<4> tacanChannelBuffer(0x1162, onTacanChannelChange);

**Comment by WarLord211** [comment]
i will check how it works and if/how we get it in the F-14

**Comment by Mabo72** [comment]
Excellent :)

**Comment by WarLord211** [comment]
Hey
can you test it?
here the F14B.lua replace that one in the lib folder. start a mission to generate the new json files.
now theres a string for the front and back radio.


[F-14B.zip](https://github.com/dcs-bios/dcs-bios/files/3039530/F-14B.zip)

**Comment by Mabo72** [comment]
Hi,

UHF 7-seg display works fine :)

**Comment by WarLord211** [comment]
Is this enough? Or is more needed?

**Comment by Mabo72** [comment]
Hey,
at the moment, probably everything :)
Thanks for the great job!

**Comment by Maverick87Shaka** [comment]
> Hey
> can you test it?
> here the F14B.lua replace that one in the lib folder. start a mission to generate the new json files.
> now theres a string for the front and back radio.
> 
> [F-14B.zip](https://github.com/dcs-bios/dcs-bios/files/3039530/F-14B.zip)

Hi, there is any updated version to use with the F14?
Trying to load your file inside my current DCSBios setup i've this error:

`2019-08-23 19:02:39.215 ALERT   EDCORE: Can't execute Lua file C:\Users\Pado\Saved Games\DCS.openbeta\Scripts\Export.lua - [string "C:\Users\Pado\Saved Games\DCS.openbeta\scripts\dcs-bios\lib\F-14B.lua"]:192: attempt to call local 'define3PosTumb' (a nil value)`

**Comment by paolorenzi** [comment]
> Hey
> can you test it?
> here the F14B.lua replace that one in the lib folder. start a mission to generate the new json files.
> now theres a string for the front and back radio.
> 
> [F-14B.zip](https://github.com/dcs-bios/dcs-bios/files/3039530/F-14B.zip)

Hi Guys i replace the lua file in the lib folder i start a new mission but DCS-BIOS don't create the new file json and i can't find the address for programm arduino.
Somebody can help me? 
I try and retry many time but nothing.
My program is to build a cockpit of the F14 with arduino.

**Comment by WarLord211** [comment]
try the latest pre release that one should work
