### ISSUE TITLE
Error on master caution adresses into the DCS BIOS User guide 0.7.0

### ISSUE THREAD

**Issue by sebj84** [dcs-bios/dcs-bios#157]
Dear DCS Bios Dev,

First of all I would like to thank you for your wonderfull Job!

Even if I'am a newbi on arduino, DCS BIOS and all programmation (I just started using you program this weekend).
I just would like to open this case to report a mistake into the "User Guide for v0.7.0".
It seems that there is an error on the references used for the "Master caution LED" on the A10.

In the documentation and for the mastercaution example you wrote:
DcsBios::LED masterCaution(0x108e, 0x0008, 13);

instead of:
DcsBios::LED masterCaution(0x1012, 0x0800, 13);

I managed to correct the problem by using the "control-reference.html" page were the values are correct.

For begginers like me it could avoid some questions if you do the correction on the documentation.

thank you again for this excellent interface you did,

Regards,

Sebj

**Comment by WarLord211** [comment]
In our fork. This is/was corrected. Thanks for the report. 

https://github.com/DCSFlightpanels/dcs-bios
