### ISSUE TITLE
NS430.lua created. Please add to the repository.

### ISSUE THREAD

**Issue by celemourn** [dcs-bios/dcs-bios#161]
Hi, I finished creating an NS430.lua to support use of the NS430 module, but I don't know how to properly add it to the repository. I'm attaching it here. Could one of you fine folks please add it in so everyone can enjoy it?  Note, I've added two new button types that might be better put into the Util.lua, but I'll let you all work that out.

Thanks!
[NS430.zip](https://github.com/dcs-bios/dcs-bios/files/3185107/NS430.zip)

**Comment by ScottyMac52** [comment]
You should create a branch locally using GIT, commit your local files to a remote version of that same branch and then create a pull request. That is the proper way of adding to the repo. Name the branch something like feature/celemourn_NS430. HTH!
