### ISSUE TITLE
How to send commands to FC3

### ISSUE THREAD

**Issue by tutushkin** [dcs-bios/dcs-bios#163]
I've created a button box with DCS BIOS on Arduino and the only issue I've stumbled is that I just don't understand what messages should I sent to control FC3 aircrafts. I fully understand that my options are limited to those assignable in a controls setup, but anyway, this is better for me than remaking the whole setup into HID gaming device.
Is there any way to send FC3 commands from Arduino via DCS BIOS?

**Comment by WarLord211** [comment]
Sorry no way to send commands via bios to fc3 planes.
The only way are to emulate key strokes. Only readouts possible

**Comment by tutushkin** [comment]
And by emulating keystrokes do you mean there is some way in DCS BIOS to do that or I should just implement some regular solution like presenting Arduino as a HID device?

**Comment by WarLord211** [comment]
Hid device or an other method for keystrokes. Bios can do for fc3 planes only readouts
