### ISSUE TITLE
trouble trying to run "connect serial port"

### ISSUE THREAD

**Issue by patogn20** [dcs-bios/dcs-bios#166]
Hey! I'm having trouble trying to run "connect serial port". it just runs and closes when double clicked. A couple of weeks ago was running ok!

Any advice?

Thanks!

**Comment by ScottyMac52** [comment]
I ran into that and a reboot fixed it. One other thing is make sure your COM port hasn't changed from when you edited it. You can set it back to ASK so you can play with different ports.

**Comment by patogn20** [comment]
Hey! thanks for your message

https://forums.eagle.ru/showthread.php?p=4087196#post4087196
