### ISSUE TITLE
Master Caution DCS-BIOS failure

### ISSUE THREAD

**Issue by ScottyMac52** [dcs-bios/dcs-bios#168]
I was following the basic setup steps and trying out the Master Caution Arduino script. Two things that I observed:

1. I hopped into a DCS F-14B Tomcat and created a master caution situation but pressing the push button did not reset it and the LED didn't blink.

2. There was an error in the log:
2019-10-20 10:25:31.443 ERROR   Lua::Config: Call error LuaExportAfterNextFrame:[string "C:\Users\Scott\Saved Games\DCS.openbeta\Scripts\DCS-BIOS\lib\CommonData.lua"]:19: attempt to index local 'selfData' (a nil value)
stack traceback:
	[C]: ?
	[string "C:\Users\Scott\Saved Games\DCS.openbeta\Scripts\DCS-BIOS\lib\CommonData.lua"]:19: in function 'v'
	[string "C:\Users\Scott\Saved Games\DCS.openbeta\Scripts\DCS-BIOS\lib\Protocol.lua"]:173: in function 'step'
	[string "C:\Users\Scott\Saved Games\DCS.openbeta\Scripts\DCS-BIOS\BIOS.lua"]:101: in function <[string "C:\Users\Scott\Saved Games\DCS.openbeta\Scripts\DCS-BIOS\BIOS.lua"]:99>.
2019-10-20 10:25:38.082 WARNING LOG: 182 duplicate message(s) skipped.

3. Running the connect-serial-port.cmd I get the following message:
Status for device COM6:
-----------------------
    Baud:            250000
    Parity:          None
    Data Bits:       8
    Stop Bits:       1
    Timeout:         OFF
    XON/XOFF:        OFF
    CTS handshaking: OFF
    DSR handshaking: OFF
    DSR sensitivity: OFF
    DTR circuit:     OFF
    RTS circuit:     OFF

Waiting for 0 seconds, press a key to continue ...
      0 [main] socat 15036 find_fast_cwd: WARNING: Couldn't compute FAST_CWD pointer.  Please report this problem to
the public mailing list cygwin@cygwin.com

Is there something systemic I am missing? My export.lua is:
local dcsSr=require('lfs');dofile(dcsSr.writedir()..[[Scripts\DCS-SimpleRadioStandalone.lua]])

local Tacviewlfs=require('lfs');dofile(Tacviewlfs.writedir()..'Scripts/TacviewGameExport.lua')

local vaicomlfs = require('lfs'); dofile(vaicomlfs.writedir()..[[Scripts\VAICOMPRO\VAICOMPRO.export.lua]])

dofile(lfs.writedir()..[[Scripts\DCS-BIOS\BIOS.lua]])

Thanks!

**Comment by WarLord211** [comment]
I checked the bios file. and via Live preview/refpage.

LED Works:
defineIndicatorLight("PLT_MASTER_CAUTION", 9200, "Warning, Caution and IndicatorLights","PILOT Weapon Panel Master Caution Light (red)")

The Button has an bug. Here the correct line:
definePushButton("PLT_MASTER_CAUTION_RESET", 34, 3056, 9199, "Weapons Panel", "PILOT Master Caution Reset")

(line 662; orginal the first Nr shows 55 correct is 34;like above)

**Comment by ScottyMac52** [comment]
Okay, I am not sure how this fixes my issue? My script is:
```#define DCSBIOS_IRQ_SERIAL
#include <DcsBios.h>

DcsBios::LED masterCaution(0x108e, 0x0008, 13);
DcsBios::Switch2Pos ufcMasterCaution("UFC_MASTER_CAUTION", 10);

void setup() {
  DcsBios::setup();
}

void loop() {
  DcsBios::loop();
}
```
Do I have make changes to the repo?

**Comment by ScottyMac52** [comment]
I see the commit now:
```
https://github.com/DCSFlightpanels/dcs-bios/commit/6009513583571567d059ff2628a46da59a81ff49
```
I will give it a try and reply back. FYI, if the LED is supposed to light with the Master Caution then that isn't working either.
