### ISSUE TITLE
F-14B addresses overlap with A-10C

### ISSUE THREAD

**Issue by danieltian** [dcs-bios/dcs-bios#169]
The output addresses for the F-14B overlap with the A-10C. This creates problems when parsing the messages from DCS BIOS because it's impossible to tell which aircraft it's for based on the message alone. For example, this is for the RIO Radar VSL Switch on the F-14B:

```
"RIO_RADAR_VSL": {
  "category": "Radar",
  "control_type": "selector",
  "description": "RIO Radar VSL Switch",
  "identifier": "RIO_RADAR_VSL",
  "inputs": [
    {
      "description": "switch to previous or next state",
      "interface": "fixed_step"
    },
    {
      "description": "set position",
      "interface": "set_state",
      "max_value": 2
    }
  ],
  "momentary_positions": "none",
  "outputs": [
    {
      "address": 4802,
      "description": "selector position",
      "mask": 24,
      "max_value": 2,
      "shift_by": 3,
      "suffix": "",
      "type": "integer"
    }
  ],
  "physical_variant": "3_position_switch"
}
```

and this is for the Compass Heading for the A-10C:

```
"COMPASS_HDG": {
  "category": "Standby Compass",
  "control_type": "analog_gauge",
  "description": "Compass Heading",
  "identifier": "COMPASS_HDG",
  "inputs": [],
  "outputs": [
    {
      "address": 4802,
      "description": "gauge position",
      "mask": 65535,
      "max_value": 65535,
      "shift_by": 0,
      "suffix": "",
      "type": "integer"
    }
  ]
}
```

Both use address 4802, so when DCS BIOS sends an update for that address, I don't know if it's for the A-10C or the F-14B. I know that I can read MetadataStart's Aircraft Name to get the current aircraft and infer it from there, but as far as I can tell, every aircraft is supposed to have its own address block that doesn't overlap with the others.

**Comment by danieltian** [comment]
I ran the JSON data through my parser for every aircraft and got the following overlaps:

Christen Eagle II overlaps with Christen Eagle I for Canopy Lever Close (Front) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Canopy Lever Close (Rear) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Canopy Jettison (Rear) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Canopy Lock (Front) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Canopy Lock (Rear) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Canopy Lever Open (Front) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Canopy Lever Open (Rear) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Canopy Unlock (Front) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Canopy Unlock (Rear) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Alternator Switch at address 10240
Christen Eagle II overlaps with Christen Eagle I for Alternator Fuse at address 10240
Christen Eagle II overlaps with Christen Eagle I for Battery Switch at address 10240
Christen Eagle II overlaps with Christen Eagle I for Volt/Ampere Meter mode (Voltage / Amperage) at address 10240
Christen Eagle II overlaps with Christen Eagle I for Fuel Pump at address 10240
Christen Eagle II overlaps with Christen Eagle I for Fuel Valve at address 10240
Christen Eagle II overlaps with Christen Eagle I for Magnets, OFF/RIGHT/LEFT/BOTH/START at address 10240
Christen Eagle II overlaps with Christen Eagle I for Mixture at address 10254
Christen Eagle II overlaps with Christen Eagle I for Propeller at address 10256
Christen Eagle II overlaps with Christen Eagle I for Left Position Light (red) at address 10258
Christen Eagle II overlaps with Christen Eagle I for Fuel Indicator mode (F / U at address 10258
Christen Eagle II overlaps with Christen Eagle I for Fuel Indicator mode Rear cockpit (F / U at address 10258    
Christen Eagle II overlaps with Christen Eagle I for Acceleration Current at address 10266
Christen Eagle II overlaps with Christen Eagle I for Acceleration Max at address 10268
Christen Eagle II overlaps with Christen Eagle I for Acceleration Min at address 10270
Christen Eagle II overlaps with Christen Eagle I for ALT 100ft Gauge at address 10274
Christen Eagle II overlaps with Christen Eagle I for ALT 1000ft Gauge at address 10276
Christen Eagle II overlaps with Christen Eagle I for ALT 10000ft Gauge at address 10278
Christen Eagle II overlaps with Christen Eagle I for Course Gauge at address 10272
Christen Eagle II overlaps with Christen Eagle I for EGT at address 10290
Christen Eagle II overlaps with Christen Eagle I for EGT Max at address 10292
Christen Eagle II overlaps with Christen Eagle I for Fuel Flow at address 10286
Christen Eagle II overlaps with Christen Eagle I for IAS Needle at address 10262
Christen Eagle II overlaps with Christen Eagle I for MANIFOLD Pressure at address 10284
Christen Eagle II overlaps with Christen Eagle I for OIL Pressure at address 10280
Christen Eagle II overlaps with Christen Eagle I for OIL Temperature at address 10282
Christen Eagle II overlaps with Christen Eagle I for RPM at address 10288
Christen Eagle II overlaps with Christen Eagle I for Vertical Speed Needle at address 10264
Christen Eagle II overlaps with Christen Eagle I for Accelerometer Reset Button at address 10240
Christen Eagle II overlaps with Christen Eagle I for Air Conditioning at address 10242
Christen Eagle II overlaps with Christen Eagle I for Smoke Switch at address 10240
Christen Eagle II overlaps with Christen Eagle I for Trim Lever at address 10244
Christen Eagle II overlaps with Christen Eagle I for Barometric Pressure at address 10246
Christen Eagle II overlaps with Christen Eagle I for Cockpit Lights at address 10260
Christen Eagle II overlaps with Christen Eagle I for Red Cockpit Lights at address 10258
Christen Eagle II overlaps with Christen Eagle I for Yellow Cockpit Lights at address 10258
Christen Eagle II overlaps with Christen Eagle I for Landing Lights at address 10258
Christen Eagle II overlaps with Christen Eagle I for Nav Lights at address 10258
Christen Eagle II overlaps with Christen Eagle I for Radio Channel at address 10240
Christen Eagle II overlaps with Christen Eagle I for Radio Frequency 25KHz (Pull) at address 10240
Christen Eagle II overlaps with Christen Eagle I for Radio Frequency 50KHz at address 10250
Christen Eagle II overlaps with Christen Eagle I for Radio Frequency MHz at address 10248
Christen Eagle II overlaps with Christen Eagle I for Radio Frequency Transfer at address 10240
Christen Eagle II overlaps with Christen Eagle I for Radio ON-OFF at address 10240
Christen Eagle II overlaps with Christen Eagle I for Radio Test (Pull) at address 10240
Christen Eagle II overlaps with Christen Eagle I for Radio Volume at address 10252
F-14B overlaps with A-10C for PILOT Compass N-S Hemisphere at address 4736   
F-14B overlaps with A-10C for PILOT Compass Mode at address 4736
F-14B overlaps with A-10C for RIO Airspeed Indicator Bug Knob at address 4616
F-14B overlaps with A-10C for RIO Weapon A/G Gun Mode at address 4814        
F-14B overlaps with A-10C for RIO Weapon Attack Mode at address 4812
F-14B overlaps with A-10C for RIO Weapon Bomb Single/Pairs at address 4814
F-14B overlaps with A-10C for RIO Weapon Bomb Step/Ripple at address 4814
F-14B overlaps with A-10C for RIO Weapon Elec Fuse at address 4812
F-14B overlaps with A-10C for RIO Weapon Interval x10ms at address 4810
F-14B overlaps with A-10C for RIO Weapon Interval x100ms at address 4810
F-14B overlaps with A-10C for RIO Weapon Jettison Racks/Weapons at address 4814
F-14B overlaps with A-10C for RIO Weapon Jettison Station 1 at address 4814
F-14B overlaps with A-10C for RIO Weapon Jettison Station 3 at address 4814
F-14B overlaps with A-10C for RIO Weapon Jettison Station 4 at address 4814
F-14B overlaps with A-10C for RIO Weapon Jettison Station 5 at address 4814
F-14B overlaps with A-10C for RIO Weapon Jettison Left Tank at address 4814
F-14B overlaps with A-10C for RIO Weapon Jettison Right Tank at address 4814
F-14B overlaps with A-10C for RIO RIO Weapon Mech Fuse at address 4812
F-14B overlaps with A-10C for RIO RIO Weapon Missile Option at address 4814
F-14B overlaps with A-10C for RIO Weapon Missile Speed Gate at address 4814
F-14B overlaps with A-10C for RIO Weapon Quantity 1s at address 4812
F-14B overlaps with A-10C for RIO Weapon Quantity 10s at address 4812
F-14B overlaps with A-10C for RIO Weapon Selective Jettison at address 4810
F-14B overlaps with A-10C for RIO Weapon Selective Jettison Aux Guard at address 4802
F-14B overlaps with A-10C for RIO Weapon Type Wheel at address 4810
F-14B overlaps with A-10C for RIO Jammer Interval Hundreds at address 4736
F-14B overlaps with A-10C for RIO ACM Threshold at address 4794
F-14B overlaps with A-10C for RIO Pulse Gain at address 4792
F-14B overlaps with A-10C for RIO PD Threshold Clear at address 4800
F-14B overlaps with A-10C for RIO PD Threshold Clutter at address 4798
F-14B overlaps with A-10C for RIO Radar IR Threshold at address 4784
F-14B overlaps with A-10C for RIO JAM/JET at address 4796
F-14B overlaps with A-10C for PILOT VDI Display Mode at address 4736
F-14B overlaps with A-10C for PILOT VDI Landing Mode at address 4736
F-14B overlaps with A-10C for PILOT VSDI Screen Brightness at address 4760
F-14B overlaps with A-10C for RIO TID Destination Mode at address 4736
F-14B overlaps with A-10C for RIO KY-28 ZEROIZE Cover at address 4688
F-14B overlaps with A-10C for PILOT Formation Light Intensity at address 4640
F-14B overlaps with A-10C for RIO Red Flood Light at address 4640
F-14B overlaps with A-10C for RIO White Flood Light at address 4640
F-14B overlaps with A-10C for RIO Console Light Intensity at address 4640
F-14B overlaps with A-10C for RIO Instrument Light Intensity at address 4640
F-14B overlaps with A-10C for RIO Radar Azimuth Center at address 4806
F-14B overlaps with A-10C for RIO Radar Azimuth Scan at address 4802
F-14B overlaps with A-10C for RIO Radar Elevation Center at address 4804
F-14B overlaps with A-10C for RIO Radar Stabilize at address 4802
F-14B overlaps with A-10C for RIO Radar VSL Switch at address 4802
F-14B overlaps with A-10C for RIO Record Reset at address 4808
F-14B overlaps with A-10C for PILOT Inboard Spoiler Override Cover at address 4736
F-14B overlaps with A-10C for PILOT Outboard Spoiler Override Cover at address 4736
F-14B overlaps with A-10C for PILOT Inboard Spoiler Override at address 4736
F-14B overlaps with A-10C for PILOT Outboard Spoiler Override at address 4736
F-14B overlaps with A-10C for RIO Record Mode at address 4802
F-14B overlaps with A-10C for RIO Record Power at address 4802
F-14B overlaps with A-10C for RIO TCS Acquisition at address 4802
F-14B overlaps with A-10C for RIO TCS FOV at address 4802
F-14B overlaps with A-10C for RIO TCS Slave at address 4802
F-14B overlaps with A-10C for PILOT High ARC-159 Frequency at address 4688
F-14B overlaps with A-10C for PILOT VHF/UHF Radio Remote Display Brightness at address 4712
F-14B overlaps with A-10C for RIO VHF/UHF ARC-182 Frequency Mode 243 MAN G PRESET READ LOAD at address 4688
F-14B overlaps with A-10C for RIO VHF/UHF ARC-182 MODE OFF T/R T/R&G DF TEST at address 4688
F-14B overlaps with A-10C for PILOT Sidewinder Volume at address 4664
Mi-8MT overlaps with Christen Eagle I for Position Lights at address 10274
Mi-8MT overlaps with Christen Eagle I for Strobe Light at address 10274
Mi-8MT overlaps with Christen Eagle I for LeftPlafond at address 10258
Mi-8MT overlaps with Christen Eagle I for PlafondBrightness at address 10256
Mi-8MT overlaps with Christen Eagle I for RecorderP503B_PanelLightness at address 10262
Mi-8MT overlaps with Christen Eagle I for RedLight5V5 at address 10254
Mi-8MT overlaps with Christen Eagle I for RedLightChGr1 at address 10248
Mi-8MT overlaps with Christen Eagle I for RedLightChGr12 at address 10252
Mi-8MT overlaps with Christen Eagle I for RedLightChGr2 at address 10250
Mi-8MT overlaps with Christen Eagle I for RedLightLhGr1 at address 10240
Mi-8MT overlaps with Christen Eagle I for RedLightLhGr2 at address 10242
Mi-8MT overlaps with Christen Eagle I for RedLightRhGr1 at address 10244
Mi-8MT overlaps with Christen Eagle I for RedLightRhGr2 at address 10246
Mi-8MT overlaps with Christen Eagle I for RightPlafond at address 10260
Mi-8MT overlaps with Christen Eagle I for WindscreenWiperL at address 10264
Mi-8MT overlaps with Christen Eagle I for WindscreenWiperR at address 10266
Mi-8MT overlaps with Christen Eagle I for R863, Frequency at address 10268
UH-1H overlaps with F-14B for ADF Frequency at address 5158
UH-1H overlaps with F-14B for ADF Signal Level at address 5160
UH-1H overlaps with F-14B for 100 Foot Counter at address 5186
UH-1H overlaps with F-14B for 1000 Foot Counter at address 5184
UH-1H overlaps with F-14B for 10000 Foot Counter at address 5182
UH-1H overlaps with F-14B for Code Off Flag at address 5194
UH-1H overlaps with F-14B for Pressure Drum Counter 0 at address 5192
UH-1H overlaps with F-14B for Pressure Drum Counter 1 at address 5190
UH-1H overlaps with F-14B for Pressure Drum Counter 2 at address 5188
UH-1H overlaps with F-14B for Altimeter Pointer at address 5180
UH-1H overlaps with F-14B for 100 Foot Counter at address 5200
UH-1H overlaps with F-14B for 1000 Foot Counter at address 5198
UH-1H overlaps with F-14B for 10000 Foot Counter at address 5196
UH-1H overlaps with F-14B for Pressure Indicator at address 5202
UH-1H overlaps with F-14B for ARMED Indicator at address 5142
UH-1H overlaps with F-14B for SAFE Indicator at address 5142
UH-1H overlaps with F-14B for ENGINE OIL PRESS at address 5140
UH-1H overlaps with F-14B for AUX FUEL LOW at address 5140
UH-1H overlaps with F-14B for ENGINE ICING at address 5140
UH-1H overlaps with F-14B for XMSN OIL PRESS at address 5140
UH-1H overlaps with F-14B for ENGINE ICE JET at address 5140
UH-1H overlaps with F-14B for XMSN OIL HOT at address 5140
UH-1H overlaps with F-14B for ENGINE CHIP DET at address 5140
UH-1H overlaps with F-14B for HYD PRESSURE at address 5140
UH-1H overlaps with F-14B for LEFT FUEL BOOST at address 5140
UH-1H overlaps with F-14B for ENGINE INLET AIR at address 5140
UH-1H overlaps with F-14B for RIGHT FUEL BOOST at address 5140
UH-1H overlaps with F-14B for INST INVERTER at address 5140
UH-1H overlaps with F-14B for ENG FUEL PUMP at address 5140
UH-1H overlaps with F-14B for DC GENERATOR at address 5142
UH-1H overlaps with F-14B for 20 MIN FUEL at address 5140
UH-1H overlaps with F-14B for EXTERNAL POWER at address 5142
UH-1H overlaps with F-14B for FUEL FILTER at address 5140
UH-1H overlaps with F-14B for CHIP DETECTOR at address 5142
UH-1H overlaps with F-14B for GOV EMER at address 5140
UH-1H overlaps with F-14B for IFF at address 5142
UH-1H overlaps with F-14B for RMI Course Pointer 1 at address 5174
UH-1H overlaps with F-14B for RMI Course Pointer 2 at address 5176
UH-1H overlaps with F-14B for RMI Heading at address 5178
UH-1H overlaps with F-14B for Rotating Course Card at address 5152
UH-1H overlaps with F-14B for From Marker at address 5150
UH-1H overlaps with F-14B for Horizontal Bar at address 5146
UH-1H overlaps with F-14B for Horizontal OFF Warning Flag at address 5156
UH-1H overlaps with F-14B for To Marker at address 5148
UH-1H overlaps with F-14B for Vertical Bar at address 5144
UH-1H overlaps with F-14B for Vertical OFF Warning Flag at address 5154
UH-1H overlaps with F-14B for Battery Switch at address 5142
UH-1H overlaps with F-14B for NON ESS BUS Switch at address 5142
UH-1H overlaps with F-14B for Starter/Stdby GEN at address 5142
UH-1H overlaps with F-14B for AC Voltage at address 5230
UH-1H overlaps with F-14B for Clock Hours at address 5240
UH-1H overlaps with F-14B for Clock Seconds at address 5242
UH-1H overlaps with F-14B for Clock Seconds at address 5244
UH-1H overlaps with F-14B for DC Voltage at address 5228
UH-1H overlaps with F-14B for Engine Oil Pressure at address 5204
UH-1H overlaps with F-14B for Engine Oil Temperature at address 5206
UH-1H overlaps with F-14B for Engine RPM at address 5218
UH-1H overlaps with F-14B for Exhaust Temperature at address 5216
UH-1H overlaps with F-14B for FIRE Warning Light at address 5142
UH-1H overlaps with F-14B for Fuel Pressure at address 5236
UH-1H overlaps with F-14B for Fuel Quantity at address 5238
UH-1H overlaps with F-14B for Gas Producer RPM at address 5224
UH-1H overlaps with F-14B for Gas Producer RPM Tenths at address 5222
UH-1H overlaps with F-14B for Low RPM Warning Light at address 5142
UH-1H overlaps with F-14B for Main Generator Load at address 5232
UH-1H overlaps with F-14B for MASTER CAUTION Light at address 5142
UH-1H overlaps with F-14B for Rotor RPM at address 5220
UH-1H overlaps with F-14B for Side Slip at address 5248
UH-1H overlaps with F-14B for STBY Generator Load at address 5234
UH-1H overlaps with F-14B for Torque Pressure at address 5226
UH-1H overlaps with F-14B for Transmission Oil Pressure at address 5208
UH-1H overlaps with F-14B for Transmission Oil Temperature at address 5210
UH-1H overlaps with F-14B for Turn Indicator at address 5246
UH-1H overlaps with F-14B for Vertical Velocity Indicator (Operator) at address 5252
UH-1H overlaps with F-14B for Vertical Velocity Indicator (Pilot) at address 5250
UH-1H overlaps with F-14B for GMC Course Pointer 1 at address 5162
UH-1H overlaps with F-14B for GMC Course Pointer 2 at address 5164
UH-1H overlaps with F-14B for GMC Heading at address 5168
UH-1H overlaps with F-14B for GMC Heading Marker at address 5166
UH-1H overlaps with F-14B for GMC Annunciator at address 5170
UH-1H overlaps with F-14B for GMC Power Fail at address 5172
UH-1H overlaps with F-14B for IFF Reply Indicator Lamp at address 5142
UH-1H overlaps with F-14B for IFF Test Indicator Lamp at address 5142
UH-1H overlaps with F-14B for HI Lamp at address 5142
UH-1H overlaps with F-14B for LO Lamp at address 5142
UH-1H overlaps with F-14B for AC GEN 1 Current at address 5134
UH-1H overlaps with F-14B for AC GEN 2 Current at address 5136
UH-1H overlaps with F-14B for AC Voltage at address 5122
UH-1H overlaps with F-14B for Anti-Ice Amperemeter at address 5138
UH-1H overlaps with F-14B for DC Battery 1 Current at address 5124
UH-1H overlaps with F-14B for DC Battery 2 Current at address 5126
UH-1H overlaps with F-14B for DC Voltage at address 5120
UH-1H overlaps with F-14B for DC VU 1 Current at address 5128
UH-1H overlaps with F-14B for DC VU 2 Current at address 5130
UH-1H overlaps with F-14B for DC VU 3 Current at address 5132
UH-1H overlaps with F-14B for IAS Front at address 5212
UH-1H overlaps with F-14B for IAS Roof at address 5214

**Comment by jboecker** [comment]
As a workaround, you could fork DCS-BIOS and modify the start offset in the call to BIOS.Protocol.beginModule at the start of an aircraft's Lua file; I'd like to avoid doing that here to keep backwards compatibility. At some point, we will have to deal with overlapping address spaces between modules anyway, to avoid running out of address space.

I could also add a feature that allows you to say "if aircraft X is active, copy address range A to B to offset X" so you could deconflict the offsets with a local config file instead of having to fork the repository.

Eventually, I want to have a feature in DCS-BIOS that allows one to build panels for a specific airframe, and then translate the export data from other airframes to the data fields from the original one. That way, the Arduino code only has to deal with addresses from one airframe (and possibly a few custom ones specific to that particular cockpit build).
For example, if you build a simpit for an A-10C but are flying some russian jet, it would translate the VVI needle position from m/s to feet per minute, cap it between -6000 and +6000 fpm, and put it at the address for the A-10C's VVI.

For external applications, I want to get rid of the binary export protocol entirely; they should be using an API that identifies export values by their name instead of magic numbers.

For multi-purpose panels, as much of the logic as possible should be migrated away from the Arduino code, possibly by adding Lua scripting to the DCS-BIOS Hub.

Is this something that would solve your current use case?

**Comment by danieltian** [comment]
Changing the binary export protocol would be great. I'm the author of [dcs-bios-api](https://github.com/danieltian/dcs-bios-api), and I'm currently using it to write a DCS BIOS plugin for the Elgato Stream Deck.

For now, I'll use `MetadataStart._ACFT_NAME` to determine if I should be processing updates for a control, so if I have an update for address 4802 and the aircraft name is "A-10C", then I'll ignore all F-14B controls at address 4802.
