### ISSUE TITLE
F-5E - Radar Elevation Antenna Tilt Control Knob

### ISSUE THREAD

**Issue by R1gh1** [dcs-bios/dcs-bios#170]
Hello,

I'm using the DCSFlightpanels/dcs-bios fork and I have an issue with the Radar Elevation potentiometer.

When playing with the value the elevation goes all way down and then only up to the middle (0 value). It is impossible to make it go over without using the "virtual cockpit" or assigned keyboard increase button.

![image](https://user-images.githubusercontent.com/38751035/67507226-cb69ac80-f68e-11e9-85b7-aa17e14a9f27.png)

In order to fix this I edited the F-5E-3.lua file as follow:

```lua
--definePotentiometer("RADAR_ELEVATION", 17, 3001, 321, {0, 1}, "Radar", "AN/APQ-159 Radar Elevation Antenna Tilt Control Knob")
definePotentiometer("RADAR_ELEVATION", 17, 3001, 321, {-1, 1}, "Radar", "AN/APQ-159 Radar Elevation Antenna Tilt Control Knob")
```

As I'm new to DCS bios I would like that someone confirm the issue and validate the patch :)

If the patch is correct can someone push a fix into the DCSFlightpanels repository?

Thank you

**Comment by WarLord211** [comment]
i checked your solution in. thanks for that

**Comment by R1gh1** [comment]
Thank you..
