### ISSUE TITLE
DCS Installation not listed

### ISSUE THREAD

**Issue by IzeHouze** [dcs-bios/dcs-bios#179]
Using the latest 0.8.2 installer, my DCS installs are not listed under the DCS Connection area.
I am able to manually copy in the line listed into the Exports.lua.  It does connect, however, LUA does not.  Yes LUA is enabled in the System Tray.

Windows 10 x64
DCS (Steam Version  Open Beta)
A-10C
F/A-18

**Comment by jboecker** [comment]
Thanks for the report, I fixed it in v0.8.3.
