### ISSUE TITLE
Category issues and EHSI course and heading knobs

### ISSUE THREAD

**Issue by mg102279** [dcs-bios/dcs-bios#195]
Hello, is there anyway you can update the categories for the F-16BLK50 to reflect panel names instead of the current names? It would be easier to help pit builders identify where every item is at. Here is a link to the picture of the F-16C Block 52. This has me confused and I have to jump to different places for one panel. I don't know where the manual pitch panel switch is at.
https://www.xflight.de/original/documents/f16c_b50.tif

Also for the EHSI the course and heading knobs are in 1 degree increments up or down and when you push the knobs in and turn they are supposed to change by 5 degree increments. This is how the real EHSI works. The mode button is fine. There is no brightness knob on the EHSI itself. I hope to see these changes soon! Thanks for providing a great product!!
Matt

**Comment by WarLord211** [comment]
what di you mean with panel names instead of real names?
i got the names from the Lua files (i dont have the plane)

since there is no push trun knob i have ti split the CRS Set / Brightness Control Knob in to two seperate switches.

**Comment by WarLord211** [comment]
fixed
