### ISSUE TITLE
KA-50 Return of Windshield wiper doesn't work well

### ISSUE THREAD

**Issue by truhlikfredy** [dcs-bios/dcs-bios#198]
The windshield wiper has a return function when doing right-click. This will put the OP_WINDSHIELD_WIPER into state 4 and keep the wiper at the default position. The OP_WINDSHIELD_WIPER supports states up to 4, but invoking the 4th state will behave the same as 3rd (slowest wiper speed) and doesn't stay in the default position. Not sure if the is doable on the DCS BIOS side, however then the 4th state is unnecessary to keep.

**Comment by WarLord211** [comment]
For the automatic funktion, i dont know any method to recreate this in BIOS.

the 4th state must be keeped, if someone has an switch like the orginal one with an magnetic reset.

**Comment by truhlikfredy** [comment]
I might look at the LUA just to see if I will spot anything obvious, tried to implement all buttons one by one, so I sorry for the reports.

**Comment by WarLord211** [comment]
no problem! so i can close this one
