### ISSUE TITLE
KA-50 WEAPONS_TARGET_RESET_BTN does press the button visually, but doesn't respond as expected

### ISSUE THREAD

**Issue by truhlikfredy** [dcs-bios/dcs-bios#199]
When invoking WEAPONS_TARGET_RESET_BTN I can see the RESET button to be pressed, but I do not see the skval reaction, nor the WEAPONS_TARGET_RESET_LED updated. However when I press it myself in the cockpit, the WEAPONS_TARGET_RESET_LED is updated and the SKVAL reacts as expected, and reading the value of the WEAPONS_TARGET_RESET_BTN is correct as well when I pressed it from the cockpit.

**Comment by WarLord211** [comment]
this is a know problem. the Maker of the lau has writen:

-- not working properly: WEAPONS_TARGET_RESET_LED

**Comment by truhlikfredy** [comment]
It looks to me that the WEAPONS_TARGET_RESET_LED might work properly when invoked correctly, but the button might not invoke something. Because the SKVAL will not get reset either. Probably it's not a problem of the LUA itself, but rather what DCS exposes to it. So then it's not really an issue for DCS BIOS, should I close it, or keep it open just so users know what issues are inherited?

**Comment by WarLord211** [comment]
Solved  looks like an DCS issue
