### ISSUE TITLE
tiny copy/paste error in A-10C profile

### ISSUE THREAD

**Issue by derammo** [dcs-bios/dcs-bios#203]
https://github.com/dcs-bios/module-a-10c/blob/bf26245f37b8ea888c1dabe967bcf411acc4d7a5/A-10C.lua#L837

the human-readable name is copied from the line above.   I would do a pull request if this is the master copy where I should pull request?  I don't understand your process well enough yet to know if the LUA is the master copy that generates the rest of the stuff.

**Comment by WarLord211** [comment]
i will correct it :) thanks for that
