### ISSUE TITLE
F-16C_50/ENGINE_TACHOMETER doesn't seem to have any value other than 0

### ISSUE THREAD

**Issue by destotelhorus** [dcs-bios/dcs-bios#205]
When trying to read the RPM of the F-16 engine I found that the F-16C_50/ENGINE_TACHOMETER isn't having any value other than 0 with current OpenBeta version.

![image](https://user-images.githubusercontent.com/13833743/72391479-81dcab00-372d-11ea-810b-eed7095f390d.png)

**Comment by WarLord211** [comment]
uploaded fix today pls try
18.01.2020
20:27 Zulu

**Comment by WarLord211** [comment]
Does it work now?

**Comment by destotelhorus** [comment]
Works like a charm now!
