### ISSUE TITLE
FA-18C Launchbar not acting correctly

### ISSUE THREAD

**Issue by Fedaykin-Wolf** [dcs-bios/dcs-bios#209]
Using Line DcsBios::Switch2Pos cbLaunchBar("CB_LAUNCH_BAR", 44); 

I have a 2pos On-Off toggle switch that I can confirm works, and it will only Raise the Launch Bar, Not Lower it

Using the controls ingame cockpit work, the switch appears to only work one way...

Thank you for your time, please let me know if you need more info

**Comment by WarLord211** [comment]
Pls try this:
https://www.dropbox.com/s/tovc2z2db2sqlfl/FA-18C_hornet.lua?dl=0

i cant test it i dont have the module

pls give feedback

**Comment by Fedaykin-Wolf** [comment]
Ok, the File I modified is:
C:\Users\feday\AppData\Roaming\DCS-BIOS\Plugins\module-fa-18c-hornet\FA-18C_hornet.lua

1) first I overwrite the old file with the one linked - Same issue

2) I undid the change in "1)" and changed only the lines 939: 
`defineToggleSwitchToggleOnly2("HOOK_BYPASS_SW", 9, 3009, 239, "Select Jettison Button", "HOOK BYPASS Switch, FIELD/CARRIER")`
To:
`defineToggleSwitch("LAUNCH_BAR_SW", 5, 3008, 233, "Select Jettison Button", "Launch Bar")`
Same result, will only raise bar not lower

in all 3 separate attempts, the LaunchBar will not Extend (which is my switch in the "OFF" State); however, it raises fine when I lower it via in-game cockpit click, then switch my custom switch to "ON" state

in so far As I can tell I am overwriting the correct file, first let me know if I am changing the correct file, since nothing i did changed anything...

**Comment by Fedaykin-Wolf** [comment]
I don't know if this helps, but the launchbar does have more to it than a normal switch, like it won't extend if the wheels don't have weight on them, or the carrier/field bypass, or of course the circuit break is pulled.

**Comment by Fedaykin-Wolf** [comment]
I got it working you can close this, it was an error on my side, I had the Circuit breaker switch setup not the actual LaunchBar Switch in arduino, sorry if I wasted any of your time for nothing :(

this line works: 
defineToggleSwitchToggleOnly2("LAUNCH_BAR_SW", 5, 3008, 233, "Select Jettison Button", "Launch Bar")

**Comment by WarLord211** [comment]
ok than i close this
