### ISSUE TITLE
Helios collaboration contact?

### ISSUE THREAD

**Issue by derammo** [dcs-bios/dcs-bios#213]
Hi DCS-BIOS team.   

I am filing this here, since I could not find a contact address for the DCS-BIOS team.

As you might have noticed from the issues I filed recently, I have been poking around DCS-BIOS.   I recently joined BlueFinBima in trying to maintain Helios and take it forward.   In that time, I have noticed that there is significant duplication of effort regarding exports and, because Helios doesn't have the large and active developer community you have, Helios is always behind.

Are you generally willing to collaborate with Helios, if it does not mean I would come to you for code?   I have been writing a lot of experiments to learn all the relevant parts and I have a few approaches that could work for Helios either leveraging or entirely using DCS-BIOS.   If you are willing to share, I would present in detail the different options and I would be happy to write all the required code.   I am sending this request because it makes little sense to go forward if you don't want to work with Helios :)

Here are some things I have done recently to get ready:

- implemented a native DCS-BIOS interface for Helios, using your 16bit integer interface
  (not likely to ship, this was just to see how it would fit)  https://github.com/derammo/HeliosExperimentation/tree/derammo_interface2/HelBIOS
- implemented the ability to generate Helios interfaces from data files instead of code for 
  many types of controls
- implemented a mock BIOS.util.* to mine the DCS-BIOS plugins for export data that isn't captured in the documentation blocks (internal DCS-facing stuff such as ids)
- cross-referenced that data against all available information from Helios to see the overlap (you obviously have way more coverage!!)
- begun work on separating the Helios functionality that assigns real world units (feet, knots, etc.) and scaling from the raw DCS data handling.  This is the main Helios interface work that really can't be automated and is probably not relevant to DCS-BIOS.
- reimplemented Helios DCS exports from scratch including support for multiple plugin formats

Based on these, I think I now have a good handle on all the pieces that would be required.

Here are some high level alternatives I could do, if you would be comfortable with any of them:

1. generate Helios interfaces from DCS-BIOS plugin mining, without any DCS-BIOS involvement
2. have the Helios export Lua implement the DCS-BIOS plugin API, so that it can run your plugins but send the data in the Helios way
3. contribute a pull request to DCS-BIOS for an additional multicast group where DCS-BIOS sends the data in a format that isn't condensed for embedded systems, specifically a TLV (type length value) format with floats and atomic strings.  This would be an option for DCS-BIOS that Helios users would turn on to get the data in full fidelity and without the memory block abstraction.  Helios could then abandon its own export scripts after a while and just require DCS-BIOS.

In all these cases, Helios would focus on assigning real world values to the raw numbers and binding them to on-screen displays.

These are just the things I have found are feasible during my experimentation.   Obviously, I really don't want to work on this if the owners of DCS-BIOS don't like it.   Hopefully you find one of the options attractive or maybe you have a better idea.   In any case, I would love to help eliminate the duplication and just have Helios use DCS-BIOS in the most sane way, which I believe Gadroc (original author of Helios) had planned to figure out before he stepped away from the project.

I can be reached on Discord at ammo#7063 or by replying here.

**Comment by WarLord211** [comment]
DCS BIOS Flightpanel Discord       https://discord.gg/5svGwKX
write me
(native german ;) )

**Comment by derammo** [comment]
Great, thanks!  I will leave this issue open a while longer in case @jboecker or other team members want to comment.
