### ISSUE TITLE
Mig-21Bis pipper position

### ISSUE THREAD

**Issue by jima72** [dcs-bios/dcs-bios#215]
Is it possible to add the gunsight pipper x/y position values? Cannot find this in the control reference. Thank you.

**Comment by WarLord211** [comment]
maybe. were can it adjusted? dont know the plane well

**Comment by jima72** [comment]
"Were can it adjusted?"
Do not understand your question.

**Comment by WarLord211** [comment]
if there is no switch/Knob for the adjustment of the piper.
via bios i have no option to get these information of X/Y
