### ISSUE TITLE
DCS BIOS 0.10.0 & Mirage 2000C all "defineString" are not workings

### ISSUE THREAD

**Issue by PetitMalin** [dcs-bios/dcs-bios#216]
Hi everyone, 

I try to display on a LCD the UHF and VUHF Frequency with the M2000C.

On the Web page"controlreference" from DCS-BIOS the display is empty 

Exemple : 
`void onUhfFrequencyChange(char* newValue) {
    /* your code here */
}
DcsBios::StringBuffer<5> uhfFrequencyBuffer(0x7332, onUhfFrequencyChange);`

I have noticed that all defineString not working for the M2000C
Exemple : 
- ECM Box EM Display
- ECM Box FLR Display
- FUEL - Fuel Flow Display
- PCN - PREP Display
Etc....

Ps: For cross tests it works well with the A10 (defineString on UHF Frequency Display)

Thank you in advance

**Comment by WarLord211** [comment]
Hi
pleas tell me which BIOS and DCS Version you use.

**Comment by PetitMalin** [comment]
Hello, Dcs Bios 0.10.0+64 and Dcs 2.5.5.41371

**Comment by WarLord211** [comment]
module was for beta 2.5.6 updated
pls made an update of the module files and try again

**Comment by PetitMalin** [comment]
THX @WarLord211  for your advise about the beta version but...
It's worse for the UHF and VHF, i have not try everything but for the radio it was better on the 1.26 version, except the display for the both who doesn't works.
Details: On the V1.26 nothing appears on Display UHF/VHF  but in the V1.23 (the last one) i have something like strange caracters on the UHF Display but nothing on the VHF display.

![UHF-Display_DCS-BIOS](https://user-images.githubusercontent.com/12863364/77590731-b075bf80-6eee-11ea-938a-c12421436bdc.png)

Ps: I can give you more details about "it was better on the 1.26" tomorrow 
Best regards

**Comment by PetitMalin** [comment]
FYI I have try on the DCS beta with the last version (1.26) result for Display UHF/VHF :
  Only a caracter & on the UHF and nothing on the VHF display.

For both version (DCS normal and beta) with the DCSBios version 1.26, for the UHF /VHF Radio eveything works except display frequency in the Controlreference (Arduino also).

With the DCSBios version 1.23 for the UHF /VHF Radio the commands INC/DEC/Toggle/Display Preset does'nt give a result on the Controlreference... but change on the pit (Not try on Arduino) but no return on the Controlreference.

That's why, i say on my last post  "it was better on the 1.26" (To start on the UHF/VHF Radio)  

![UHF-Display_DCS-BIOS](https://user-images.githubusercontent.com/12863364/77669591-507e2800-6f85-11ea-9365-0ad1e4dad9e0.png)
![VHF-Display_DCS-BIOS](https://user-images.githubusercontent.com/12863364/77669599-5411af00-6f85-11ea-9e8f-18c354179460.png)
Best regards

**Comment by WarLord211** [comment]
ok we will have a look

**Comment by WarLord211** [comment]
Would you test this version?

https://www.dropbox.com/s/fgwkom4yj2scw8b/M-2000C.zip?dl=0

**Comment by PetitMalin** [comment]
HI @WarLord211, I tested the new version it's great, it works !!! (UHF / VHF) Thank you for your excellent work, I have other modules in preparation. If I find other problems in other modules I will bring it up. Thank you again, take care of yourself and your family.

**Comment by PetitMalin** [comment]
HI @WarLord211, i tested the new version, it's great it works !!! (UHF / VHF / FUEL /PCN) 
Thank you for your excellent work. Just one last thing, the ECM Box looks like the starting problem from UHF/VHF, to know no display (Copy below).
![DCS-BIOS_ECM](https://user-images.githubusercontent.com/12863364/78398221-ffa8a800-75f2-11ea-93e6-34b4f9977fc5.png)
Thank you again, take care of yourself and your family.

**Comment by WarLord211** [comment]
This is an leftover from the old cockpit. 
in the new cockpit the box is gone.

**Comment by PetitMalin** [comment]
@WarLord211 sorry for the delay... Ok recorded 
Thank's again for your work ++
