### ISSUE TITLE
MI-8MT R-863 dials jumping over digits not synced with cockpit

### ISSUE THREAD

**Issue by jdahlblom** [dcs-bios/dcs-bios#218]
Easy to replicate, open CTRL-REF and in cockpit dial e.g. R-863, 10MHz Rotary Knob. At some stage CTRL-REF will show digits being skipped.
For example now when I have been testing (decreasing) it goes from 1 to 9 and skipping 0.
This makes DCSFP's sync procedure go bonkers.

DCS Stable 2.5.4
DCS-BIOS  0.7.34

**Comment by WarLord211** [comment]
Found the Fix, uploaded in 0.7.XX master
