### ISSUE TITLE
Changing Radio preset sets invalid frequency in game

### ISSUE THREAD

**Issue by talbotmcinnis** [dcs-bios/dcs-bios#219]
I am using SRS to monitor the effective/actual frequency that my radios are using.  Note this is NOT related to the manual selected frequency displayed on the radio panel.

Tuning, and setting presets works great whether I do it in-pit, or via DCS-bios.

However, tuning presets has an odd behavior.  With the radio in PRE mode, switching PRESET should cause the saved preset to become the effective frequency and thus appear in SRS.  However when my DCS-BIOS hub receive the PRESET_INC or DEC, the effective frequency snaps to some new freq (121.5? from vague memory).

I've just barely started to look into this, but I am suspicious of A10-C.lua:1047 which appears to set the radio frequency in game.  Is the possible this method is being called after the preset changes?  I couldn't see what calls that method to see if something is going wrong with the freq that is sent into that method.  It really shouldn't be called at all when the preset changes.

**Comment by talbotmcinnis** [comment]
Update: I tried commenting out that stuff from A10-C.lua:1047 and it made no difference.

I also tested without SRS and no other DCS-exports, and still had the same issue so this very much appears to be an issue isolated to DCS-Bios.

**Comment by WarLord211** [comment]
hi
if i understand correct there is an problem with the preset.
Which radio?
BIOS version?
and what exactly?

**Comment by talbotmcinnis** [comment]
Hi!
You are correct there is an issue with the radio preset knob.
I have confirmed the issue affects VHF_FM and VHF_AM.  I believe it also affects UHF but I have not confirmed that.
I installed version v0.10.0, and confirmed that the issue presents when using the controls reference button i.e. has nothing to do with the arduinos.

Steps to recreate:
Jump in a running A-10.
Set VHF-AM to TR mode.
Set tuning to MAN.
Tune 80.000Mhz.
*IN-GAME* Set preset dial to 01.
Press Load.
Tune 90.000Mhz.  Observe warning tone.
*IN-GAME* Set preset dial to 02.
Press Load.
Change VHF tuning to PRE.
*IN-GAME* Set preset dial to 01.  Observe no tone, i.e. it worked radio is tuned to 80Mhz.
*IN-GAME* Set preset dial to 02.  Observe tone, i.e. it worked radio is tuned to 90Mhz.
*IN-GAME* Set preset dial back to 01.  Observe no tone.
In DCS-BIOS (via controls reference), send PRESET_INC.  Observe preset dial move to 02, Expect: Radio is tuned to 90 Mhz and the tone is heard.  Actual: Radio is tuned to some other fixed frequency and no tone is heard.

To be clear, I am not TRYING to tune the warning frequency, but it is an easy debug-aid to tell if the radio was properly tuned without using SRS or comms.

**Comment by WarLord211** [comment]
Ok. I will test it.
This works ingame without bios?

I ask because bios does nothing else,  as "klick" the buttons as an user. So I dont know if that's an bios problem.

**Comment by talbotmcinnis** [comment]
Correct, it works in game even without dcs-bios.  It works in dcs-bios is running and you use the in-game preset dial.  It does not work if dcs-bios issue the preset-knob inc or dec.  the knob does change but the radio frequency is also set/overridden and it should not be.

If I can help please let me know.  Im happy to do a screen-share or do some debugging if it would help.  Thanks so much for looking into this!

**Comment by WarLord211** [comment]
ok i can reproduce it. i think it cames from the preset switch itself. 
i put that tone to Preset 3 and after some switching it apears on 7 so counting is bad or something.
i had to dig in.

**Comment by talbotmcinnis** [comment]
Im glad you were able to confirm the issue.  Best of luck debugging and don’t hesitate to reach out if I can help debugging in any way.

**Comment by WarLord211** [comment]
So after some research we have an test:
https://www.dropbox.com/s/7y1jqi9c9m2w691/A-10C.rar?dl=0

override the old files.

**Comment by talbotmcinnis** [comment]
Very exciting!  I will try tonight!

**Comment by talbotmcinnis** [comment]
Hey, this works GREAT.  Tested VHF FM, AM and both perform correctly.  I'm so happy right now, thank you!   Just in time for me to start training with the 476th where I think I'm going to be using them A LOT.

**Comment by talbotmcinnis** [comment]
I will leave the issue open in case you have a merge process to wrap this up, but as far as I am concerned this is resolved.

**Comment by WarLord211** [comment]
resolved
