### ISSUE TITLE
Spitfire Primer mess with trim

### ISSUE THREAD

**Issue by PrestaMath** [dcs-bios/dcs-bios#223]
Vesion of DCS open beta : 2.5.6.50979
DCS-BIOS Version: v0.10.0+64 (21e288cdeb95f54d1b5c4935fde9e51ae3c58965)

Hello,

Even in the DCS bios hub web interface when I try to do a "primer pump turn", i can see the trim turning to full down slowy
Also the primer pull seems not to be working.

Anyway thanks a lot, with your work I have made a cockpit where I have 70 % ok knobs, switches, potentiometers, encoders that are working great and allow to get a really good feeling when flying. Also i use udp data to display instruments on an android tablet.

Best regards

**Comment by WarLord211** [comment]
fixed in HUB and Flightpanel fork

for Hub simply make an update

thx for submitting this bug. if you have more pls let me know

**Comment by PrestaMath** [comment]
Thanks Warlord for the reactivity !

But i made the update and everything no longer worked.
By commenting  the 2 lines related to BIOS.util.define3Pos2CommandSwitchWW2 the export run again :)

Seems that my lua has no define3Pos2CommandSwitchWW2

Now I can prime my engin 👍 

Best regards

**Comment by WarLord211** [comment]
should be fixed too

**Comment by PrestaMath** [comment]
Last commit fail with
`2020-06-30 19:18:44.532 ALERT   EDCORE: Can't execute Lua file C:\Users\Math\Saved Games\DCS\Scripts\Export.lua - [string "C:\Users\Math\AppData\Roaming\DCS-BIOS\Plugins\module-spitfire-lfmkix\SpitfireLFMkIX.lua"]:151: attempt to call global 'define3Pos2CommandSwitchWW2' (a nil value)`

in your last commit you removed : 
`local define3Pos2CommandSwitchWW2 = BIOS.util.define3Pos2CommandSwitchWW2`

Best regards

**Comment by WarLord211** [comment]
ok next try.
i cant test it since i dont use the hub version

**Comment by PrestaMath** [comment]
ok it is working straight with the hub update.

I will continue to add feature to my cockpit and then check every elements.

Thanks
