### ISSUE TITLE
DCSBios causing flood of dcs.log messages

### ISSUE THREAD

**Issue by talbotmcinnis** [dcs-bios/dcs-bios#225]
I just took a peak at my DCS log message, latest Open Beta, flying A-10.  I see a stream of these messages over and over again:

	ERROR   Lua::Config: Call error LuaExportAfterNextFrame:[string "C:\Users\Talbot\AppData\Roaming\DCS-BIOS\Plugins\module-commondata\CommonData.lua"]:20: attempt to perform arithmetic on upvalue 'ias' (a nil value)
	stack traceback:
	[C]: ?
	[string "C:\Users\Talbot\AppData\Roaming\DCS-BIOS\Plugins\module-commondata\CommonData.lua"]:20: in function 'v'
	[string "C:\Program Files\DCS-BIOS\dcs-lua\lib\Protocol.lua"]:169: in function 'step'
	[string "C:\Program Files\DCS-BIOS\dcs-lua\BIOS.lua"]:85: in function <[string "C:\Program Files\DCS-BIOS\dcs-lua\BIOS.lua"]:83>.

Sounds like a missing nil value check?  Cheers.

**Comment by WarLord211** [comment]
should fixed long time. 
pls do an update and try again

**Comment by talbotmcinnis** [comment]
I believe I am on the latest bios-hub and up to date but I will check tonight to confirm versions.  Thanks:)

**Comment by talbotmcinnis** [comment]
According to the DCS-BIOS Hub web terminal, I have DCS-BIOS Version: v0.10.0+64 (21e288cdeb95f54d1b5c4935fde9e51ae3c58965) which I believe to be the latest.

**Comment by talbotmcinnis** [comment]
Oh wait, I found updates for plugins for module-a-10c and module-commondata.  Will fly tonight and check logs afterwards.

**Comment by talbotmcinnis** [comment]
Will indeed.  That error is gone.  New one showed up but I think just once on startup, so much less of a concern:

2020-07-09 23:46:30.488 ERROR   Lua::Config: Call error LuaExportAfterNextFrame:[string "C:\Users\Talbot\AppData\Roaming\DCS-BIOS\Plugins\module-a-10c\A-10C.lua"]:110: attempt to concatenate local 'freq1' (a nil value)
stack traceback:
	[C]: ?
	[string "C:\Users\Talbot\AppData\Roaming\DCS-BIOS\Plugins\module-a-10c\A-10C.lua"]:110: in function 'getter'
	[string "C:\Program Files\DCS-BIOS\dcs-lua\lib\Util.lua"]:723: in function 'v'
	[string "C:\Program Files\DCS-BIOS\dcs-lua\lib\Protocol.lua"]:169: in function 'step'
	[string "C:\Program Files\DCS-BIOS\dcs-lua\BIOS.lua"]:85: in function <[string "C:\Program Files\DCS-BIOS\dcs-lua\BIOS.lua"]:83>.

**Comment by WarLord211** [comment]
will be fixed soon
allways check vor plugin updates. in the next time there will no BIOS "HUB" updates and ic will do some bug fixing for the plugins. but no new stuff will come.

for new stuff look on my fork of the preHub version of BIOS

Edit: Fix is up pls test

**Comment by WarLord211** [comment]
Problem solved? can it be closed?

**Comment by talbotmcinnis** [comment]
Oops sorry, yes I checked my logs last night and they were clean.
