### ISSUE TITLE
F16 Trottle IDLE/OFF binding

### ISSUE THREAD

**Issue by MikeKilo** [dcs-bios/dcs-bios#233]
Hello all,

While I am aware that HOTAS functions usually aren't exposed in the DCS BIOS controls, I was wondering if there is a way to add the F16 throttle detents, as it is rarley implemented on HOTAS devices.
Is there a way to send a specific keybinding to the sim directly and not an actual control? that can be a nice bypass for almost every control that does not exist in DCS BIOS.

Thanks for all the great work!

**Comment by WarLord211** [comment]
Im sorry but not possible, because there no arguments and commands. And booth are the fundament of BIOS.
