### ISSUE TITLE
A-10 IFF Master Mode issues

### ISSUE THREAD

**Issue by talbotmcinnis** [dcs-bios/dcs-bios#237]
I am wiring up the IFF panel for A-10.

First, the CODE dial should have a multi pin implementation in the control reference, not just inc/dec.

Second, the sample code for MASTER has 9 as the array size but should be just 5.  I wonder if this indicates a bigger issue though, as when I used it with 5, I can only get positions 0 and 1 to send messages?

**Comment by WarLord211** [comment]
After quick look only at the code:

CODE has an strange code. must test and deep look

which sample code you mean? in the lua it has only 5 "steps"

**Comment by talbotmcinnis** [comment]
In the controls reference, this is what I can copy:

const byte iffMasterPins[9] = {PIN_0, PIN_1, PIN_2, PIN_3, PIN_4}
DcsBios::SwitchMultiPos iffMaster("IFF_MASTER", iffMasterPins, 9);

The array and third parameter should be 5, not 9.

Despite that, I seem to be able to get pin_0 to send a 0, pin_1 to send a 1, but cannot get anything beyond that to work.  When I activate any other pin, I get only a 3 out but never a 2 or a 4.

Thanks for investigating CODE.  The HOLD position is momentary, but from the outside, I see no reason why it needs to be any different.  Ignorance is bliss I'm sure there is some trickery under the hood.  Good luck, let me know if I can help!

**Comment by talbotmcinnis** [comment]
I should be clearer:  CODE works fine as a SwitchMultiPos... the issue is just that the Controls Reference only gives a RotaryEncoder example.

This works:

const byte iffCodePins[4] = {2,1,0,27};
DcsBios::SwitchMultiPos iffCode("IFF_CODE", iffCodePins, 4);

but should be documented as such.

**Comment by talbotmcinnis** [comment]
Adding to the fun, the TEST LED seems to work perfectly, but the REPLY LED is always on despite toggling in game.

**Comment by WarLord211** [comment]
From BIOS Point all Fine with the lights. (Argument Right) should be an ED issue

![2020-08-19](https://user-images.githubusercontent.com/10798954/90653342-57ad1780-e23f-11ea-9755-ce97651318cf.png)
MASTER i cant reproduce. Works fine for me. (im not using HUB)

CODE every thime i i programm it an other way, it stops working. So i would take it as it is now.

After Todays Beta Patch i look if something changes and compare my fork to the A-10 from Hub and make updates if needed.

You use Hub right?

**Comment by talbotmcinnis** [comment]
I do use hub on my flight sim pc.  

Much of my testing of the master issue is simply inspecting the serial output.

Ill do more testing tonight, including testing my inputs on a different control to confirm its not a wiring issue.

**Comment by talbotmcinnis** [comment]
Confirmed the MASTER issue is okay now; pinout confusion.  Sorry 'bout that one!

**Comment by talbotmcinnis** [comment]
Confirmed (as you suspected), that my CODE dial is sending the right commands on the serial port, but has no effect on DCS.

I also confirmed that regarding the LEDs, DCS-HUB does indicate the same values I see on my panel (REPLY always on, TEST always OFF) and as they change in game, those values do not change at all.

Lastly, confirming that MASTER is okay end-to-end, 100% now.  I assume the screenshot you posted of the documentation is to be released later?

**Comment by talbotmcinnis** [comment]
I just ran a test of the infamous kapt-zeen helios profile, and confirmed that the reply and test LEDs both function properly... which I think confirms that DCS is wired up properly to export the status of those two LEDs.  Does that help?  Is there anything I could capture from that export which would help point to the right exports to monitor?

The CODE dial also works from the zeen profile, so we may have good leads to go off of.

**Comment by WarLord211** [comment]
my suspection is the the problem lies on HUB. Wiht our fork (Flightpanel BIOS, uses the older 0.7 as base but stand of last beta patch) via refpage i cant find errors.

as i sayd after i upload the new stuff to ouir fork i will compare the booth a-10 to get the HUB version the last version

**Comment by talbotmcinnis** [comment]
I've been digging into the helios code, and the have a pull request merged in (https://github.com/BlueFinBima/Helios14/pull/162) which says it fixes some of the IFF functions, and in doing so they change the 
IFF REPLY LAMP from 798 to 795.
IFF TEST LAMP from 799 to 796.

I see that the DCS A10C module uses 798 and 799.  I wonder if it's a simple as changing those valus?

I'm not clear how to test that though. :)  Cheers.

**Comment by WarLord211** [comment]
795 and 796 are the Push arguments not the Light arguments.

----------------------------------------------------

I have tested booth with the Live Preview.

if i push the Test Button the light comes up.
i get from booth (Light and Button) an 1. when i pressed the Button (via mouse and live preview)

so i cant find an error sorry

----------------------------------------------------

Also booth Luas are almost the same so no need for an update for HUB

**Comment by talbotmcinnis** [comment]
Thanks for looking at it.  I'm not sure what steps to take next.  Is there any logging built in, so I could record what did happen?  Or is building/debugging dcs-bios hub a good way to solve this?  

I am a competent software debugger but I need a little nudge in the right direction.

I had a new issue tonight where one of my Arduino devices appears to have malfunctioned, and as a result the whole dcs-bios hub closed all serial ports from all devices, rendering my pit nearly useless.

I would love to help contribute to the project.  Should I pull the source for dcs-bios and start a visual studio debug session?  I want to help the project and a little conformation that this is the right approach would help.

**Comment by talbotmcinnis** [comment]
What is "live preview"?  Maybe I'm missing a tool that would help?

**Comment by WarLord211** [comment]
old tool from DCS BIOS 0.7.XXXX, should in some kind in HUB but i dont know exactly. 

There you have an interface were you see "in" and "outputs" and can interact with the Ingame cockpit.
Reference page / live Preview ... are some names of it

the development of the HUB is on hold for an undefined Time.  Im updating only some modules if gamebraking bug are discovered.
I push the BIOS of the preHub version forward.

https://github.com/DCSFlightpanels/dcs-bios (stand last beta update 26.8. / all mods planes,... )

may contacte me via discord ( found in the readme page)

**Comment by talbotmcinnis** [comment]
Quick update here: I switched from HUB to FlightPanels/dcs-bios and the IFF LEDs do indeed work perfectly.  CODE does not, but I also admit it has no function so I wouldn't consider this a priority issue at all.
