### ISSUE TITLE
F-14 UHF Channel display

### ISSUE THREAD

**Issue by janpitor** [dcs-bios/dcs-bios#240]
Good evening,

I need to export the UHF1 (ARC-159) preset channel display. The channels displayed range from 1-20. However the only snippet I have found is "PILOT UHF ARC-159 Preset Channel Selector", which is the actual physical position of the cockpit encoder which changes the selected channel. This has range of 1-10, which doesn't help at all.

Am I looking wrong and there is a specific snippet for the displayed channel, or alternatively is there any possibility to export it from DCS in different way?

Thank you

**Comment by WarLord211** [comment]
I upload the latest version of the F-14.
pls check if this solve the problem.

**Comment by janpitor** [comment]
Good evening,

thank you very much for the fast response. However, it did not solve the
problem. I saw you increased the range of the parameter, but the problem
is, if you for example turn the wheel to the left and you get to channel 1
on the display, you can still turn the wheel and the PILOT UHF ARC-159
Preset Channel Selector parameter will still cycle 10 9 8 7 6 5 4 3 2 1 10
9 8 7 6 5 etc. So I think the only solution is to read a different
parameter (the channel selected), which is not yet in dcs bios.

I hope I described the problem better.

Thank you for your work again

Best regards

Jan

ut 6. 10. 2020 o 17:11 Sven <notifications@github.com> napísal(a):

**Comment by WarLord211** [comment]
the switch is not connected with the number you see.
the plane switch is an "infinite switch" you can turn his as long as you want ingame, but only count from 1 to 20 or 20 to 1

i dont know i the reference/live preview page is still in HUB (i use the flightpanel fork). But there i can switch in the ranges like the switch ingame works.

**Comment by janpitor** [comment]
Yes, there is nothing wrong with the switch, but I need to read the
display, not the switch

ut 6. 10. 2020 o 18:37 Sven <notifications@github.com> napísal(a):

**Comment by WarLord211** [comment]
PLT_UHF_REMOTE_DISP
RIO_UHF_REMOTE_DISP
PLT_VUHF_REMOTE_DISP

**Comment by janpitor** [comment]
Oh, I didnt realize the remote display shows the channel too. You are
right, this will work for me. Thank you again so much

ut 6. 10. 2020 o 19:06 Sven <notifications@github.com> napísal(a):

**Comment by janpitor** [comment]
But, I dont see any of these remote displays in dcs bios, only the test and
brightness controls for them.
Or is there different way to get the data from the sim?


ut 6. 10. 2020 o 20:03 Ján Pitor <janpitor@gmail.com> napísal(a):

**Comment by WarLord211** [comment]
PLT_UHF_REMOTE_DISP  -   PILOT UHF ARC-159 Radio Remote  ,   UHF 1   ,   exported as string 
RIO_UHF_REMOTE_DISP - RIO UHF ARC-159 Radio Remote ,   UHF 1   ,   exported as string 
PLT_VUHF_REMOTE_DISP - PILOT VHF/UHF ARC-182 Radio , VUHF  ,   exported as string

**Comment by janpitor** [comment]
Ok, thank you

ut 6. 10. 2020 o 20:58 Sven <notifications@github.com> napísal(a):
