### ISSUE TITLE
F-16C CMDS

### ISSUE THREAD

**Issue by Mabo72** [dcs-bios/dcs-bios#241]
Hi,

I have a problem with the items below. Can I ask you to check their correctness?

DcsBios::StringBuffer<4> cmdsO1AmountBuffer(0x4580, onCmdsO1AmountChange);
DcsBios::StringBuffer<4> cmdsO2AmountBuffer(0x4584, onCmdsO2AmountChange);
DcsBios::StringBuffer<4> cmdsChAmountBuffer(0x4588, onCmdsChAmountChange);
DcsBios::StringBuffer<4> cmdsFlAmountBuffer(0x458c, onCmdsFlAmountChange);

**Comment by WarLord211** [comment]
I upload the latest version of the F-16.
pls check if this solve the problem.

**Comment by Mabo72** [comment]
Still not working :(

**Comment by WarLord211** [comment]
try the newes version pls

**Comment by Mabo72** [comment]
Now it works perfectly :)

**Comment by WarLord211** [comment]
perfekt
