### ISSUE TITLE
F-16c-50 changes break DCS-BIOS Hub

### ISSUE THREAD

**Issue by slindj** [dcs-bios/dcs-bios#242]
function define3Pos2CommandSwitch definition was removed from F-16C_50.lua to instead be:

`local define3Pos2CommandSwitch = BIOS.util.define3Pos2CommandSwitch`

However, BIOS.util doesn't have a definition for define3Pos2CommandSwitch.  As a result DCS-BIOS stopped connecting to DCS for all modules.

**Comment by WarLord211** [comment]
Thanks.
should fixed now

**Comment by slindj** [comment]
Thanks!  Really appreciate your work on this!
