### ISSUE TITLE
Problem with DCS-Bios hub reading data from DCS (Win 10)

### ISSUE THREAD

**Issue by wartech0** [dcs-bios/dcs-bios#244]
Hey Guys,
I've been having an issue getting DCS-Bios to read data from DCS, currently I can change panels via the control reference toggles in DCS hub but it never reads anything. Looking at the DCS.log yields this interesting tidbit.

`2020-12-04 08:41:08.177 ERROR   Lua::Config: Call error LuaExportAfterNextFrame:<LUA_TTABLE>
stack traceback:
	[C]: ?
	[C]: in function 'try'
	[string "C:\Program Files\DCS-BIOS\dcs-lua\lib\ProtocolIO.lua"]:98: in function 'send'
	[string "C:\Program Files\DCS-BIOS\dcs-lua\lib\ProtocolIO.lua"]:170: in function 'flush'
	[string "C:\Program Files\DCS-BIOS\dcs-lua\BIOS.lua"]:86: in function <[string "C:\Program Files\DCS-BIOS\dcs-lua\BIOS.lua"]:83>.`

I took a look at where its having an issue and I found it specifically has an issue here in ProtocolIO.lua

`socket.try(self.conn:sendto(msg, "239.255.50.10", 5010))`

I will attach the entire DCS [dcs.log](https://github.com/dcs-bios/dcs-bios/files/5641618/dcs.log) file but as far as I can tell this is the only error I get, I thought it could be a firewall issue so I also disabled my firewall completely and added custom rules allowing DCS hub through the firewall. I also investigated the DCSBios.log and there is nothing in it, but the file is created its just empty. Is anyone else experiencing this issue?

**Comment by wartech0** [comment]
Hey Guys,
Quick update I figured it out!
It was hamanchi this entire time, so DCS Bios does not play well with hamanchi, you have to disable the adapter if you have it installed, I figured I would leave this issue open just in case because I could find no information about this online.
Thanks

**Comment by tao-jcqt** [comment]
Thanks man, I don't know how to thank you more for what you have posted here. I've been trying for months to find a solution to make DCS Bios work with outputs and I didn't understand the problem. Thanks to you I can finally use DCS BIOS to read data from DCS, as you were Hamachi who was the problem from the beginning... Thanks again !!!!

**Comment by wartech0** [comment]
> 
> 
> Thanks man, I don't know how to thank you more for what you have posted here. I've been trying for months to find a solution to make DCS Bios work with outputs and I didn't understand the problem. Thanks to you I can finally use DCS BIOS to read data from DCS, as you were Hamachi who was the problem from the beginning... Thanks again !!!!

Yea man I saw your other stuff online in the DCS forums and such as I was like "this guy is having the exact same issue!" I finally thought to check the code to see where it was having issues and I took a wild guess about Hamanchi being the issue. Anyway happy that you finally got it working!

**Comment by WarLord211** [comment]
i will note this in our troubleshooting guide.

do you mean Hamachi  the "LAN over Internet" programm?
i dont know hamanchi

**Comment by wartech0** [comment]
> 
> 
> i will note this in our troubleshooting guide.
> 
> do you mean Hamachi the "LAN over Internet" programm?
> i dont know hamanchi

Yes that specific program, I had to disable the hamanchi interface in the windows network adapters and it worked.
