### ISSUE TITLE
cannot find json

### ISSUE THREAD

**Issue by zhkmxx9302013** [dcs-bios/dcs-bios#246]
Q:
when I open the plugin catalog, there is an error pop out, showing " could not fetch plugin catalog: could not fetch JSON catalog". what shoud I do.

**Comment by zhkmxx9302013** [comment]
oh， I found the git link,

**Comment by jackwongtongxian** [comment]
Hi, 
I got the same issue: localhost:5010 could not fetch plugin catalog: could not fetch json catalog
Could you please advise how to solve it? Thanks.
