### ISSUE TITLE
Mode OVRD switch in the F-16

### ISSUE THREAD

**Issue by destotelhorus** [dcs-bios/dcs-bios#255]
Can the DGFT-Mode / MRM mode switch be added to DCS-BIOS, please?

**Comment by WarLord211** [comment]
? were is this switch?

is it clickable?
i cant find anything in the Module code.

**Comment by destotelhorus** [comment]
The switch is on the Thrustlever I am afraid.

**Comment by WarLord211** [comment]
its not clickable to no chance with BIOS

**Comment by destotelhorus** [comment]
Alright, thank you for checking! closing it then!
