### ISSUE TITLE
F16 DED

### ISSUE THREAD

**Issue by elvinsilvester** [dcs-bios/dcs-bios#257]
Hi,

When selecting the tacan air-air mode, the distance towards the tanker is not shown on the DED when activated if returned back to uhf/vhf main page. 

In-game it IS showing on the DED when flying towards the tanker; at the right bottom side on the DED were normally the tacan airport freq is shown. 

When switching off tacan air-air mode, the normal tacan freq for airports are shown as correct.

**Comment by WarLord211** [comment]
Uploaded fix.
pls test it

**Comment by elvinsilvester** [comment]
Hi! 

Did the update like you said and tested.. 

Now i have "no" export at all on the DED.. it's not showing anything anymore on the DED that's displayed from in-game. 

What can i do to fix it, or can you roll back the update/fix you did.

**Comment by WarLord211** [comment]
roll back done

**Comment by elvinsilvester** [comment]
Tested and everything works good again, without off course the distance data towards tanker. 

Thanks for trying! Think the update wasn't correct. Hope you can find a solution.
