### ISSUE TITLE
I want to contribute, but need some pointers

### ISSUE THREAD

**Issue by matkuscz** [dcs-bios/dcs-bios#259]
Hi,
first of all, thanks a lot for your work everyone here. Amazing piece of software. 
Now, I'm working on my first hardware panel. One thing I still not understand is how you, or other projects, get data from DCS... I know that you are connected to some Lua environment running inside DCS by socket. But how do you know which functions can you call and what objects live there ? I have found [this](https://www.digitalcombatsimulator.com/en/support/faq/scripting_engine/). I see no definitions for F-14 there but you have pretty much every parameter of F-14 available...Is it possible to add more params for Flaming Cliffs modules? For ex. weapons panel - selected pylons on A10-A? Or things for Su-25T ? It's free and I love flying it, so maybe more people would be interested in that...I don't want it from you, just point me to some start...Are you data mining those values from running memory? Or do you call some DCS API and there are no more detailed data  available for FC modules? What is the general approach ?
I would love to add those values for FC3 modules...
Thanks again for all your work,
Peace

**Comment by WarLord211** [comment]
for FC3 modules only some rudementary readouts possible. see here a list: https://wiki.hoggitworld.com/view/DCS_Export_Script

for the other aircrafts the data copmes from there cockpit luas. in short readouts of argument states (switches, etc)
FC3 modules dont have these chanes. 
as example. if you turn on the APU the defined switch dont move in cockpit. there is no interaction with the pit.
in full simulated moduels there is.

i checked the Commondata.lua and the FC3.lua (booth are affected by FC3 modules) and there the latest version.
