### ISSUE TITLE
AV8B Harrier UFC Preset Strings Fix

### ISSUE THREAD

**Issue by taipan303** [dcs-bios/dcs-bios#264]
AV8BNA module defined strings "UFC_COMM1_DISPLAY" and "UFC_COMM2_DISPLAY" are displaying 2 preset characters from a 4 character string. E.g. ": 22" will store " :" in UFC_COMM1_DISPLAY when it should store "22".

It's only a 2 character max length defined string. The stored string needs to be from the last 2 characters instead of the first 2.

Change line 673 and 679 to "return (" "):rep(2 - #txt) .. txt:sub(3,4)" fixes the issue.
Tested successfully in lua console and hub script.

**Comment by WarLord211** [comment]
added to booth BIOS versions  (HUB+Flightpanels)

**Comment by taipan303** [comment]
Great thanks!
