### ISSUE TITLE
F-5E Requests

### ISSUE THREAD

**Issue by taipan303** [dcs-bios/dcs-bios#265]
The "F-5E-3/AUTOBAL" command only works to move the switch left, center and right don't respond with either 0,1,2 or INC,DEC.

Also there is no mapping for the Radar Cursor Brightness. The control labelled as Pitch Knob has the control "F-5E-3/RADAR_CURSOR" but it controls the pitch knob not the cursor brightness.

Can a control be added for the Radar Cursor Brightness?

Thanks!

**Comment by WarLord211** [comment]
Radar Cursor Brightness was a typo is fixed and uploaded.

For the auto balance is a new switch needed, atm not fixable.

**Comment by taipan303** [comment]
Thanks
