### ISSUE TITLE
UH-1H ADF Band does not allow to select LOOP mode

### ISSUE THREAD

**Issue by ESA-Angel** [dcs-bios/dcs-bios#266]
Hello, I am building an ADF panel with DCS-bios.
https://www.youtube.com/watch?v=YJVejne-Q0I

I have a problem and it is that although the simulator allows to operate all the ADF modes (adf, ant and loop), DCSBios does not allow to select the latter.

Looking at the reference control I see that it only allows to select two of the three positions

Could you fix this? LOOP mode is more important and interesting than ANT and my radio will be incomplete without it

Thanks!

**Comment by WarLord211** [comment]
can you give me an BIOS name? (that one you write in the arduino code)
i tested all switches with the refpage and cant find a problem

**Comment by ESA-Angel** [comment]
I've been trying all the options...

//ADF Mode with rotary 4 positions only off,adf and ant
const byte adfModePins[5] = {2,3,4};
DcsBios::SwitchMultiPos adfMode("ADF_MODE", adfModePins, 5); 

// with switch on-off-on , only select OFF,ADF y ANT
DcsBios::Switch3Pos adfMode("ADF_MODE", 2, 3); 

// with encoder, go from off, adf to ant and go back to the beginning.No select loop
DcsBios::RotaryEncoder adfMode("ADF_MODE", "DEC", "INC", 9,8); 

none works for me

**Comment by WarLord211** [comment]
via ref page i can switch to all 4 modes.

**Comment by ESA-Angel** [comment]
And your code is the same as mine?
I have not been able to select the Loop mode in any way 

I have used this from control reference

const byte adfModePins[5] = {PIN_0, PIN_1, PIN_2}
DcsBios::SwitchMultiPos adfMode("ADF_MODE", adfModePins, 5);

**Comment by WarLord211** [comment]
my bad i try the flightpanel fork files i saw the HUB files are way behind update incoming

**Comment by WarLord211** [comment]
fix uploaded - maybe some address changes

**Comment by ESA-Angel** [comment]
Perfect, I didn't have to touch anything in the code and everything works!

https://www.youtube.com/watch?v=4QHOf7fxa-0

Danke schön!!!

**Comment by WarLord211** [comment]
gerne :)
