### ISSUE TITLE
Cant get the Console lights potentiometer to work in my f22 home cockpit 

### ISSUE THREAD

**Issue by Lkirchner1234** [dcs-bios/dcs-bios#314]
I have tried a bunch of other variables in f22 with the same potentiometer and they work. For some reason however the console lights doesnt work. This is my code: DcsBios::Potentiometer consoleLightsSw("CONSOLE_LIGHTS_SW", 2); . I put it in the IRQserial example and it doesnt work. Any help would be great.

**Comment by WarLord211** [comment]
This BIOS version doesnt support the F-22. its this one: (https://github.com/DCSFlightpanels/dcs-bios)

error found and fixed. (typo) uploaded to master
