### ISSUE TITLE
16-bit I/O expander

### ISSUE THREAD

**Issue by hans0611** [dcs-bios/dcs-bios#33]
I have been using the "old" DCS-BIOS version (experimental branch) with UNO + Ethernet shield W5100 with great success.

In order to expand the numbers of I/O I have been trying to apply a 16-bit I/O expander MCP23017. The origianl idea came from this; http://macetech.com/store/index.php?main_page=product_info&products_id=23

I have tried with a small setup using only one MCP23017 and it works great with "old" DCS-BIOS version. It is very simple to use since instead of digitalWrite you just need to type CS.digitalWrite.
I wonder if it was possible to incorporate the use of 16-bit I/O expanders in the DCS-BIOS as it would greatly increase the numbers of I/O (up to 128 ~ 8 MCP23017)

Great work by the way
ED forum ID: HMA

**Comment by jboecker** [comment]
Closing this, as `ExportStreamListener` and `PollingInput` are now documented.
