### ISSUE TITLE
Connecting to VRinsight Devices questions.

### ISSUE THREAD

**Issue by BrassEm** [dcs-bios/dcs-bios#39]
G'day, I have some questions about how to go about connecting up some commercial COM devices (from VRinsight) via multicast-console.cmd. The devices I have to use are the CDUII and MCP2B units on COM8 and COM13.

These devices are preconfigured in their COM data which is text based. With the VRinsight software interface example, I have used Visual Studio 2013 C++ to write a UDP client to talk with DCS via the DCS-BIOS software on 127.0.0.1:7778 with sendto(). This sends the commands successfully to DCS from both the CDU and MCP via multicast-console.cmd.

I need to get data from DCS to the MCP. When I run multicast-console.cmd I don't see the multicast data like I do with connect-serial-port.cmd. 

Is the multicast-console.cmd sending cast data via 239.255.50.10:5010? Or does that command need to be added to the multicast-console.cmd?

I know I can unrem the BIOSConfig.lua for the :7777 recfrom() and program for it, but I was hoping for "out of the box" functionality if :5010 were cast.

**Comment by jboecker** [comment]
multicast-console.cmd is only meant for debugging (to manually send data to DCS).
It used to display data from DCS, but I switched that off when I introduced the binary export protocol.

If you implement your own C++ client, you won't need to run any of the scripts that come with DCS-BIOS. Those are meant to get the export data to an Arduino that is connected to a serial port and knows how to parse the DCS-BIOS protocol.

To get data from DCS-BIOS, see the developer guide on how to get the data stream.
Then, feed the data you receive byte for byte into the `ProtocolParser` class that you can find in the [DCS-BIOS Arduino Library](https://github.com/dcs-bios/dcs-bios-arduino-library/blob/master/DcsBios.cpp#L10).
Replace [lines 55 and 56](https://github.com/dcs-bios/dcs-bios-arduino-library/blob/master/DcsBios.cpp#L55) with a call to a method of your choice (this is the point where a write access to a specific address has been decoded).

To know the meaning of the values written to specific addresses, consult the control reference documentation in advanced mode. You can also look at the `StringBuffer`, `LED` and `ServoOutput` classes in the Arduino Library for examples.

**Comment by jboecker** [comment]
I am closing this issue since it looks like you got it working.
Thanks for your contribution to the wider DCS-BIOS ecosystem!
