### ISSUE TITLE
Altitude Gauge Question

### ISSUE THREAD

**Issue by OlHall** [dcs-bios/dcs-bios#43]
In order to create an altitude gauge, I'm guessing a stepper motor would need to be used rather than a servo (to provide complete rotation, two needles, etc.).

1. Is that a correct assumption, and
2. does DCS-BIOS provide support for this kind of thing or would this be something I'd need to develop myself?

**Comment by jboecker** [comment]
Your assumption is correct.
Currently, there is no stepper motor support in DCS-BIOS. You would use this snippet (from the reference docs) inside `onDcsBiosWrite()` to update a variable with the target position:
````
if (address == 0x107e) {
    unsigned int alt100ftValue = (value & 0xffff) >> 0;
    /* your code here */ // save value to somewhere
}
````
You would then call some code from your loop() function that keeps track of the stepper position and moves it towards the target position.

In the future, after the changes that Gadroc is working on right now have been merged into the Arduino library, the code snippet above would be replaced by the use of an `IntegerBuffer`, which will work similar to the current `StringBuffer`.
