### ISSUE TITLE
Huey armament indicators not working?

### ISSUE THREAD

**Issue by OlHall** [dcs-bios/dcs-bios#45]
First of all, apologies if I'm doing something stupid but I'm able to get the master caution/RPM warning lights to work fine, but cannot get the armament safe/armed lights to function.

How does the DCS id (254, 255) get mapped onto the address/bitmask?  e.g. How does 255 map onto 0x1416, 8th LSB?  I presume the "base" address of 0x1400 probably relates to that?

I've used the code from the control reference:
DcsBios::LED safeInd(0x1416, 0x0020, PIN);

But I changed the name of the LED object - would that matter?
DcsBios::LED weaponsSafeInd(0x1416, 0x0020, 30);

Any pointers would be gratefully received!

**Comment by jboecker** [comment]
The variable name does not matter. The code you posted should work.
I'll try to look into this tonight (off to work now).

Can you check if the [interactive control reference documentation](https://www.youtube.com/watch?v=MoVoa-BUOkQ) shows the correct value? If it does, it's a bug on the Arduino side. If it doesn't, it's a bug on the DCS-BIOS side in UH1H.lua.

**Comment by OlHall** [comment]
Hi,
The interactive mode in Chrome is very cool - but it isn't updating correctly.  The controls work (as in Master Arm Off - Safe - Armed functions), but the status indicators aren't showing any feedback.

Unfortunately, I'm not even sure if DCS is correctly updating the indicators as I can't get a view point where I can see the panel in the cockpit, and I can't turn off the pilot body! So frustrating!

**Comment by jboecker** [comment]
I read a while ago that you can move the viewpoint around with the mouse when holding the middle mouse button, maybe that helps.

The DCS argument numbers are mapped to DCS-BIOS outputs by lines 64 and 65 in UH1H.lua:
````lua
defineIndicatorLight("ARMED_IND", 254, "Armament Panel", "ARMED Indicator")
defineIndicatorLight("SAFE_IND", 255, "Armament Panel", "SAFE Indicator")
````
This is no different from all the other indicator lamps. Either there is something special about these two or we are missing something here.

I am sitting at work right now twiddling my thumbs while the server that has the code I need to work on is undergoing scheduled maintenance. Might as well go back to my dorm room to look at this bug and work remotely when that server has finished its file system checks.

**Comment by OlHall** [comment]
Hi - thanks for using you spare time on this ;-)
I managed to get rid of the pilot body (I had to enable/disable it in the OPTIONS/MISC menu) and now he's finally gone.  I can now see the panel, and the lights do function in the virtual cockpit - they just don't seem to be reporting/mapping correctly back in DCS-BIOS :(

[I am currently messing with this when I should be doing my job - so I'd better get back to work!  At least the boss won't shout at me (as it's me) but I still feel a bit guilty!]

**Comment by OlHall** [comment]
I've just checked the MAIN_PANEL/lamps.lua in the DCS Huey aircraft section and it looks pretty normal:

    lamp_ARMED            = create_default_lamp(254, controllers.ARMED)
    lamp_SAFE             = create_default_lamp(255, controllers.SAFE)

I'm assuming that the first param is the DCS id of the control/indicator, but I still don't get how that maps onto the bitmap addresses (e.g. how does 91-110 map onto 0x1414-0x1416)?

**Comment by jboecker** [comment]
defineIndicatorLight calls moduleBeingDefined.memoryMap:allocateInt({ maxValue = 1}), which returns a "memory allocation" in the DCS-BIOS export address space (maybe "address space reservation" would be a more accurate term here). It gets mapped to the next free location.

Addresses are mostly assigned in the order that the space is allocated. Exceptions happen when a partially allocated 16-bit block does not have enough "free bits" to allocate the current value. In that case, the current value gets allocated in the next 16-bit block, but subsequently allocated values that  are small enough to fit into the "gap" (such as a 1-bit indicator light value) will be allocated there.

**Comment by OlHall** [comment]
Excellent - it sounds super-efficient.

**Comment by jboecker** [comment]
I have confirmed that it is a bug in DCS-BIOS.

* Start the UH-1H mission "Rebel base" in single player
* hop into the "hot start" Huey
* Press Alt+C. Now you can look around with the mouse and move the camera position when holding the middle mouse button. Get the Armament Panel into view, then press Alt+C again to get back to "interaction mode"
* open the control reference docs
* click the Armed/Safe/Off switch in the cockpit
* note that the switch position is correctly shown in the reference docs, but the state of the indicator lights is not

**Comment by jboecker** [comment]
For some reason, when a light is on, the cockpit argument for these indicators is not 1.0.
Instead, I get a slightly different "almost 1.0" every time, e.g.

0.98221737146378
0.98239517211914
0.98256683349609

I have modified defineIndicatorLight() so it treats all non-null values as "on". The fix is in the master branch now.

**Comment by OlHall** [comment]
Brilliant - thanks very much!

I wonder if the value is presented as an intensity value, rather than a binary one (and may be affected by things like brightness pots?)

**Comment by jboecker** [comment]
After some more investigation, the argument value depends on the battery DC voltage.
Once the DC voltage drops below about 22V, the argument value becomes less than 0.5 and the indicator light in the cockpit turns off.

I have modified defineIndicatorLight() accordingly.

To reproduce:
* hop into a cold start Huey
* turn on the battery switch
* (optional: preserve sanity by turning off the "low RPM audio" switch)
* arm weapons to illuminate the ARMED indicator lamp
* on the overhead panel, set the the "VM" dial to "BAT"
* observe the indicator lamp and the DC voltmeter while engaging the starter in short bursts to drain the battery
