### ISSUE TITLE
Is it possible to define additional input support for controls?

### ISSUE THREAD

**Issue by OlHall** [dcs-bios/dcs-bios#47]
For example, the Huey ADF Tune is currently configured as a rotary encoder input.

    420 defineRotary("ADF_TUNE", 27, 3003, 39, "ADF", "ADF Tune") 

I'd like to implement this using a multi-turn potentiometer - can I add this?

    ... definePotentiometer("ADF_TUNE", 27, 3003, 39, {0, 1}, "ADF", "ADF Tune")

Even if this is feasible, I expect I've gotten the values wrong!

**Comment by jboecker** [comment]
To do that, you would have to determine the exact interaction between the ADF_TUNE control (device 27, command 3003, rotation of the knob available as cockpit argument 39) and the ADF_FREQ output (cockpit argument 45).

You would have to figure out what `performClickableAction` calls to make to get cockpit argument 45 to a specific value.

If that is possible at all, it would require a lot of experimentation in the Lua Console, as nothing of this stuff is documented (and sometimes you run into situations where certain small or large step sizes simply do nothing, such as with the VHFCOMM_VOL control).

**Comment by OlHall** [comment]
lol - not trivial then ;-)
