### ISSUE TITLE
Huey: raltDisplayBuffer(0x14aa) - spurious characters

### ISSUE THREAD

**Issue by OlHall** [dcs-bios/dcs-bios#49]
Hi,

I'm taking the value from the StringBuffer (using Gadroc's new code, though it was the same with the older StringBuffer callback mechanism) and presenting it on an LCD panel.
Occasionally I get spurious characters in the 4 char buffer.  After looking over the arduino library code, I suspect this is what's being received over serial from dcs-bios.
It's possible that this is what DCS is putting out, but is it possible that the string data is being corrupted along the way?

Cheers,
Oliver

**Comment by jboecker** [comment]
Please check if the interactive control reference documentation shows the same behavior.

If it does, it's a bug on the Lua side.
If it doesn't, something is going wrong on the way to the Arduino or in the Arduino code itself.

Also, do you have steps to reproduce this somewhat reliably, i.e. how spurious are we talking? Once in a blue moon or once every minute?

**Comment by OlHall** [comment]
Hi,
I've checked the interactive control (sorry I hadn't done this already) and it's fine there, so it looks like something in the arduino code.

It's hard to put a figure on how often it's corrupt, but it's pretty regular - say 1 in 20 updates?  Strangely, the bad characters usually appear as "U", and often in pairs.

**Comment by OlHall** [comment]
Bizarrely, another thread has just made me realise - the 'U's are the sync bytes (0x55) aren't they? so it looks like the string data is being incorrectly parsed in the Arduino library.

**Comment by OlHall** [comment]
Is it possible that this is a timing thing?  I'm running at 500000 baud - too fast? too slow?

**Comment by mblackham** [comment]
I'm at 128000 with no issues seen.

**Comment by jboecker** [comment]
In general, there are two possible sources for this kind of error.

1. Transmission errors
2. Defining too much controls (because the serial RX code is not optimized yet)

Reducing the baud rate can help with both up to a point. Try 115200.
The default of 500000 was a bad choice -- it worked fine with my toy problems, so I figured I might as well use it if it means 5ms less latency or something.

**Comment by OlHall** [comment]
I'll drop my baud and close this for now - and reopen if I get future issues
