### ISSUE TITLE
Arduino compile error

### ISSUE THREAD

**Issue by mblackham** [dcs-bios/dcs-bios#50]
Getting a compile error on first try.....

Arduino: 1.6.0 (Windows 7), Board: "Arduino Uno"

dcs-bios-arduino-library-master\Protocol.cpp.o: In function DcsBios::ProtocolParser::processChar(unsigned char)': C:\Users\Mark\Documents\Arduino\libraries\dcs-bios-arduino-library-master/Protocol.cpp:64: undefined reference toonDcsBiosFrameSync()'
collect2: error: ld returned 1 exit status
Error compiling.

Any suggestions?

**Comment by OlHall** [comment]
I had this too - I think there is currently a bit of a mismatch between the example sketches/docs and the efficiency improvements that have recently been made.

If you declare a new function in your sketch such as:
    void onDcsBiosFrameSync() {
    ...
    }
then it'll compile, but if you're using any code inside `onDcsBiosWrite(unsigned int address, unsigned int value)` this will no longer be called.

Instead, you need to (I think) test the dirty flags of any String or IntegerBuffers to see if there's new information to update.  LEDs and inputs should work fine though.

Good luck!

**Comment by OlHall** [comment]
this should probably be in the dcs-bios-library section too!

**Comment by mblackham** [comment]
As a quick fix I rem'ed the DcsBiosFrameSync() section of the Protocol.ccp

It compiled and the arduino is get data (I judge from the flashing led) but The pin 13 LED won't light up on TACAN test LED lighting.

Will try your idea too.

**Comment by mblackham** [comment]
Un rem'ed and stuck 
void onDcsBiosFrameSync() {
}
into sketch.  Compiled fine and cmd.exe is running happily but still no pin 13 LED.... puzzleed

**Comment by mblackham** [comment]
![cmd output](https://cloud.githubusercontent.com/assets/11075467/6271039/0a52ad24-b856-11e4-8dd8-f74f7eeae703.jpg)

Should the U's be there?

**Comment by OlHall** [comment]
Yep – they’re the comms protocol sync bytes

 


http://www.ultamation.com/images/logomail2.gif

OLIVER HALL
Managing Director
T: +44 (0)151 331 5210
M: +44 (0)7867 546 916
 <http://www.ultamation.com/> www.ultamation.com

 

* Winners of “Most Creative GUI” at the 2013 Crestron Integration Awards

* Programmers for a major winning entry at the 2012 Crestron Integration Awards

* Programmers for 2 winning entries at the 2011 Crestron Integration Awards

* Winners of "Most Creative Interface" at the 2010 Crestron Integration Awards

**Comment by mblackham** [comment]
Lol yea... I realised that after I posted it by comparing with the intro vid on youtube.

**Comment by mblackham** [comment]
would my baud setting be an issue?  Got it set to 128000

**Comment by OlHall** [comment]
Well... if it's different at each end, then yes - definitely!  The standard baud of the example Ardunio code and the `connect-serial-port.cmd` is 500000 baud.

Arduino Sketch
```
Serial.begin(500000);
```

connect-serial-port.cmd
```
mode COM%COMPORT% BAUD=500000 PARITY=N DATA=8 STOP=1 TO=off DTR=on
```

**Comment by mblackham** [comment]
Na it's the same both ends.  My cheap "unduino" maxes out at 128000.

Just wondered if reducing that would have any affect.

**Comment by OlHall** [comment]
As long as they're the same it should work!  How have you defined the LED object?

```
DcsBios::LED tacanTest(0x10da, 0x0400, 13);
```

**Comment by mblackham** [comment]
Exactly that....  hence the confusion :/

**Comment by mblackham** [comment]
Update... bought a proper official arduino board and works great.

Avoid CH340 chips.
