### ISSUE TITLE
MiG-21 development question

### ISSUE THREAD

**Issue by wraith444** [dcs-bios/dcs-bios#53]
Is anyone working on MiG-21 support for DCS-BIOS? If not or if they are and need assistance, what skills will be necessary to do so?

**Comment by jboecker** [comment]
As far as I know, no one is working on that right now.

To add support for an aircraft module to DCS-BIOS, you need the following:

* own the aircraft module (duh)
* know the module well so you can quickly make an educated guess about which virtual cockpit control the piece of code you are looking at in `clickabledata.lua` corresponds to
* know (or learn) Lua basics to get the syntax right and to interactively debug things in the DCS Witchcraft Lua Console

I'd estimate the effort to add the complete module at about three days full-time work (I did the A-10C over a long weekend).

If you are interested in contributing Mig-21 support, I'll gladly help you get started via Skype or TS.

**Comment by mblackham** [comment]
A long weekend.....  lol that's amazing.

**Comment by wraith444** [comment]
I don't have any background in Lua, but I do have some experience via a
couple classes with Visual Basic and am picking up on coding for Arduino. I
also own the MiG-21 module and am fairly familiar with it.

I don't want to waste your time before I'm ready to start working. Where
should I start with learning Lua, and what points should I cover before
starting on the MiG?

**Comment by jboecker** [comment]
The Developer Guide has a section on adding your own aircraft module:
http://dcs-bios.a10c.de/docs/v0.2.4/developerguide.html#_adding_a_new_aircraft_module

For information about Lua, you can consult the Lua 5.1 Reference Manual:
http://www.lua.org/manual/5.1/

But don't worry about wasting my time. The current documentation is probably enough for someone who already knows a lot about DCS: World internals, but I want to improve it. Walking you through adding the first few switches would help me figure out how to do that -- after hacking on this stuff for half a year, I simply lack the perspective of someone who is new to the concept of Export.lua.

If you have programmed in any other language before, I am confident that after an hour or two, I'll have you up and running. I want to show you how to experiment with the Lua Console and reload DCS-BIOS without reloading the simulator. If you can quickly try a different piece of code after discovering an error, you will learn the rest a lot faster.

PM me ([FSF]Ian) on the ED forums and we can set something up.
