### ISSUE TITLE
UH-1H Huey, ADF frequency (0-65535, UH-1H/ADF_FREQ)

### ISSUE THREAD

**Issue by jdahlblom** [dcs-bios/dcs-bios#55]
I am implementing ADF in Flightpanels and stumbled upon this.
According to docs the frequencies are 190 to 1750 kHz. Can someone fix this? 190 -> 0, 1750 -> 65535 ?
Will there be a String output?

Thanks!

**Comment by OlHall** [comment]
The docs are wrong - the range is 190-1800.  You also have to be careful because the scale isn't linear.  The code below will take the freq dial position, and convert it to the appropriate frequency (based on a "band" index of 0-2).

```
unsigned int adfConcordance[6][6] = {
  {   0,  47,  91, 138, 1000,    0 },   // 190-400 kHz
  { 190, 195, 200, 211,  400,    0 },
  {   0,  49,  98, 151,  202, 1000 },   // 400-850 kHz
  { 400, 411, 420, 425,	 450,  850 },
  {   0,  49, 102, 151, 1000,    0 },   // 850-1750 kHz (actually 850-1800?)
  { 850, 875, 900, 950, 1800,    0 }
};

unsigned int adfScaledFreq( unsigned char band, unsigned int value )
{
  unsigned int lowI = value, lowF = 0, highI = value, highF = 0;
  unsigned char idx = 0;
  unsigned char bandIdx = band << 1;
  for( idx=0; idx<5; idx++ )
  {
    if( value <= adfConcordance[bandIdx][idx+1] )
    {
      lowI  = adfConcordance[bandIdx][idx];
      highI = adfConcordance[bandIdx][idx+1];
      lowF  = adfConcordance[bandIdx+1][idx];
      highF = adfConcordance[bandIdx+1][idx+1];
      break;
    }
  }
  
  return map( value, lowI, highI, lowF, highF );
}
```

**Comment by OlHall** [comment]
Apologies - the code above assumes the AdfFreq has been pre-scaled to 0-1000 using a class that hasn't been (and may never be!) pulled into the master branch.

I define the import variables like this - you can use the standard IntegrBuffer which will yield the normal 0-65535 range, but then you'll have to change the scale of the frequency concordance table to make it work out.
```
// ADF
DcsBios::IntegerBuffer        adfBand( 0x14fc, 0x0003, 0 );
DcsBios::MappedIntegerBuffer  adfFreq( 0x1426, 0xffff, 0, 0, 65535, 0, 1000 );
```

And then these are displayed (to an LCD screen), if they change, at the end of each update frame.
```
void onDcsBiosFrameSync()
{
  // ADF
  if( adfBand.isDirty() )
  {
    lcdADFFreq();
    adfBand.clearDirty();
  }
  
  if( adfFreq.isDirty() )
    lcdADFFreq();
}

**Comment by jdahlblom** [comment]
Thanks for the information, I'll be able to get something based on this.
Den 5 mar 2015 16:07 skrev "Oliver Hall" <notifications@github.com>:

**Comment by jdahlblom** [comment]
But they are linear within each band aren't they? Damn difficult to lean into the cockpit and view the frequency from straight above the panel.

**Comment by OlHall** [comment]
Not in the slightest! ;)

**Comment by jdahlblom** [comment]
Here are our observations of the offsets. Anyone here know math enough to get a function from these values? Possible to create a new table with extrapolated values in between observed values?

![2015-03-12_184102](https://cloud.githubusercontent.com/assets/10453261/6623240/63942116-c8ea-11e4-8d7b-2697a93c8003.jpg)

**Comment by OlHall** [comment]
I don't follow - the code I posted above does what you're asking (I believe) and I used the concordance tables directly from the dcs Huey lua config.  And 1750 *isnt* the top end.

**Comment by jdahlblom** [comment]
Ok, C++ is unknown to me. Can you explain?
Den 12 mar 2015 19:13 skrev "Oliver Hall" <notifications@github.com>:

**Comment by OlHall** [comment]
Dcs-bios is great in that you can a lot without needing to know c++ (as long as you follow the rules), but I think explaining c++ syntax is a bit beyond this thread - the mapping logic isn't complicated once you get past the syntax.

**Comment by jdahlblom** [comment]
Thanks again!
