### ISSUE TITLE
MiG-21bis landing gear lights export not working

### ISSUE THREAD

**Issue by jdahlblom** [dcs-bios/dcs-bios#59]
Following controls shows (UP / DOWN) 1 or 0 at the same time. Does not follow the 3 red or 3 green lights in the cockpit (manual p. 48, indicators #45-50).

MiG-21Bis/GEAR_NOSE_DOWN
MiG-21Bis/GEAR_NOSE_UP
MiG-21Bis/GEAR_RIGHT_DOWN
MiG-21Bis/GEAR_RIGHT_UP
MiG-21Bis/GEAR_LEFT_DOWN
MiG-21Bis/GEAR_LEFT_UP

**Comment by WarLord211** [comment]
fixed - Lights work inverted
