### ISSUE TITLE
P-51 support

### ISSUE THREAD

**Issue by toxaq** [dcs-bios/dcs-bios#68]
Dumb question but I can't seem to find a consistent answer. Is the P-51 supported?

**Comment by mblackham** [comment]
All clicka le cockpits are "supported" but each needs implementing by
someone.  Don't thing anyone's done the P51 yet.

**Comment by toxaq** [comment]
Cheers mblackham. I guess that's where I'm getting confused as to what is supported about a clickable cockpit... Basically I built a little rev counter with a stepper and I can move it with an arduino via serial. I'd like to send the RPM count from DCS for a P51 to my arduino. I've got the socat example all setup but I don't own A10-C to test the master switch light (and I can't dump to serial while socat is connected).

Any advice on where to look to extract that info from DCS? Can I dump the info out into a log file to find the addresses for this data etc? I'm not really sure on where to start.

**Comment by mblackham** [comment]
Find the documentation for dcsbios on github.  There is an explanation on
how to export the clickable cockpit data for different modules.

I've not tried it my self but I have used the released version of dcsbios
to run various switch panels for the A10C so k ow it works.

**Comment by toxaq** [comment]
Ok, thanks. I found this document which seems to clear things up a bit better for me. http://deadfrogstudios.com/warthogpit/index.php?title=Exporting_DCS_Data

**Comment by mblackham** [comment]
Nice.  Start it up via github and people will help you out.  Might have a
look myself too

**Comment by toxaq** [comment]
@mblackham So i've got throttle, RPM, landing gear lights and RPM gauge working. 

Took a while to work out where to pull out all of the info from though! Might need to fork the docs for others but if anyone is reading this you'll need the main_panel_init.lua (for P51 at least) and to find the device references, device.lua and for the buttons clickabledata.lua. All very logical in the end but with lots of variables from hardware through arduino through socat bi-directionally there's a lot that can go wrong!

I'll fork this next weekend and try and organise my progress.

**Comment by toxaq** [comment]
My starting point on the P-51. Whilst only 5 inputs, they do all work
https://github.com/toxaq/dcs-bios/blob/master/Scripts/DCS-BIOS/lib/P51D.lua
