### ISSUE TITLE
Help request with DCS Bios

### ISSUE THREAD

**Issue by hossamzayed** [dcs-bios/dcs-bios#69]
Hi I'm trying to build a sim pit based on DCS , and I have read the DCS BIOS documentation , but couldn't quite understand how to get simple row data from DCS like pitch and roll. 
Below is a standard arduino DCS code. I just want to know what to write in the dotted space in front of the pitch and roll to get their values from DCS. Thank you

#include <DcsBios.h>
#include <Servo.h>

DcsBios:: ProtocolParser parser;

void setup() {
Serial.begin(9600);
}

void loop() {
// feed incoming data to the parser
while (Serial.available()) {
parser.processChar(Serial.read());
}

double roll = ................... ;
double pitch = ................... ;

// poll inputs
DcsBios:: PollingInput::pollInputs();
}

void onDcsBiosWrite(unsigned int address, unsigned int value) {

}

**Comment by jboecker** [comment]
Answered on the ED forums. Please have some patience instead of spamming all available channels with the same question.

**Comment by hossamzayed** [comment]
Hi,

I'm really sorry if I offended any one with my repeated post. I had no intention for spamming. I was merely seeking knowledge. Kindly re open my issue and help me if possible at achieving my goal for learning

 Best regards,
 
Eng. HOSSAM ZAYED
Owner & founder
 

Inception Engineering Consultancy Firm


4 Ahmed Mohamed Kamal Street 
Ground Floor | District 8
Nasr City 11787 | Egypt

Tel.   : +20 2 2287 8841
Mob : +201060777090

Info@inception-egy.com

www.inception-egy.com
 

On Sep 2, 2015, at 12:35 PM, jboecker <notifications@github.com> wrote:

Closed #69.

**Comment by toxaq** [comment]
You've left this in like 5 places that I know if. I've answered you in one of them but you haven't replied there so I'm sure you could see why that would be frustrating.

**Comment by hossamzayed** [comment]
I'm sorry , it is really non intentional. 
I had my accounts in different forums confused. I haven't seen your reply if that what you mean , and I appreciate your effort. I have received this post via email and that's why I was able to see it. Thank you again. 

 Best regards,
 
Eng. HOSSAM ZAYED
Owner & founder
 

Inception Engineering Consultancy Firm


4 Ahmed Mohamed Kamal Street 
Ground Floor | District 8
Nasr City 11787 | Egypt

Tel.   : +20 2 2287 8841
Mob : +201060777090

Info@inception-egy.com

www.inception-egy.com
 

On Sep 7, 2015, at 12:11 AM, Scott <notifications@github.com> wrote:

You've left this in like 5 places that I know if. I've answered you in one of them but you haven't replied there so I'm sure you could see why that would be frustrating.
