### ISSUE TITLE
Arduino Due dont work/ Arduino Uno Works?? 

### ISSUE THREAD

**Issue by David8080** [dcs-bios/dcs-bios#70]
Hi.
I have a strange problem whit my Arduino Due.
It sends some strange thinks to the dcs-bios and there for it does not work.
My Arduino Uno works good.
And my Uno card is blink "TX" in DCS, but my Due blink "RX"?? I dont have the skill to
know whats wrong here:(
Here is 2 picture from the Dcs-Bios, first is my Uno, then its a picture of the same but
whit my Due.As you can see somthing is wrong.
Anyone that knows whats wrong.??
Thanks
![1](https://cloud.githubusercontent.com/assets/14128941/9689081/d66ada62-5333-11e5-9541-a14e4604bfe0.jpg)
![2](https://cloud.githubusercontent.com/assets/14128941/9689092/e4fe271e-5333-11e5-9cd3-8b7764fcd1ca.jpg)

**Comment by jboecker** [comment]
I am not familiar with the Due and don't have one to reproduce this, but apparently it has both a "programming" and a "native" USB port. The default "Serial" object is mapped to the programming port.

Try communicating over the native USB port instead (which should show up as another virtual COM port on your PC) by replacing each occurrence of "Serial" with "SerialUSB" in your sketch.

You could also try different baud rates (250000 or 115200). To do that, change the baud rate both in the connect-serial-port.cmd script and in your sketch in the Serial.begin() line.

**Comment by David8080** [comment]
Thanks for your reply.
I will try this and i let you know how it works.
I did order a mega2560 but i will try this anyway and let you know if it works.

Thanks
