### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by flyn28261** [dcs-bios/dcs-bios#82]
I don't know if it is an issue or just me (super new to coding got my arduino a week ago).  I am getting a compiling error. I follow your readme and used the included example with no luck.  Any help you could give me would be greatly appreciated. 

Arduino: 1.6.7 (Windows 7), Board: "Arduino/Genuino Uno"

Build options changed, rebuilding all
C:\Users\Matt\Documents\Arduino\libraries\dcs-bios-arduino-library-master\examples\MasterCaution\MasterCaution.ino:8:62: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]

 DcsBios::Switch2Pos masterCautionBtn("UFC_MASTER_CAUTION", 10);

                                                              ^

libraries\dcs-bios-arduino-library-master\Protocol.cpp.o: In function `DcsBios::ProtocolParser::processChar(unsigned char)':

C:\Users\Matt\Documents\Arduino\libraries\dcs-bios-arduino-library-master/Protocol.cpp:64: undefined reference to `onDcsBiosFrameSync()'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by jboecker** [comment]
The master branch is the bleeding edge development version and is not guaranteed to work.
Use the most recent [release version](https://github.com/dcs-bios/dcs-bios/releases) instead.

Which instructions did you follow? If there is a document out there that points newcomers to the master branch, I need to fix that.

**Comment by flyn28261** [comment]
I will change the version and try again.  

This is the document I was using:
dcs-bios/Scripts/DCS-BIOS/doc/userguide.adoc
