### ISSUE TITLE
A10C Anti Skid Switch not working

### ISSUE THREAD

**Issue by adrianfourie** [dcs-bios/dcs-bios#84]
Hi DCS Bios Team,
First of all: GREAT JOB on the DCS Bios for Arduino. So much potential in this program. Makes it so easy for us beginners. Cheers for that!

Bug with A10C: 
Not sure if it has been reported,but there is a bug with the Anti Skid switch in A10C.(Landing Gear and Flap Panel)  It fails to switch.
I see in the Forums it has been discussed.

Regards,
Adrian

**Comment by jboecker** [comment]
Works fine for me. I will need more detailed information than "it fails to switch".

What have you tried? (Post your code!)
What did you expect to happen?
What happened instead?

Note that the Anti-Skid switch is not a normal two-position toggle switch but an electrically held switch, like the SAS switches.
