### ISSUE TITLE
Caution light panel

### ISSUE THREAD

**Issue by Thirtykay** [dcs-bios/dcs-bios#85]
[Uploading 1f37b5c0b44aec0d3f80-7eb02999f68afeed20811cf957ce2445e31cdee7 (1).zip…]()

Hello,

i need help for the sketch of my caution light panel that i will build. My question is simple , can you help me to adapt the sketch you've made 1 year ago to get it compatible with the actual dcs bios version , sorry for my bad english and thank you.

**Comment by jboecker** [comment]
I assume you are referring to this sketch:
https://gist.github.com/jboecker/1f37b5c0b44aec0d3f80

I have updated it now to work with the current version of the Arduino library.
