### ISSUE TITLE
Button doesn't work for me

### ISSUE THREAD

**Issue by Mattack-1412** [dcs-bios/dcs-bios#86]
I downloaded DCS BIOS yesterday and have made an LED blink with the master caution but my button for the master caution doesn't work. Is it possible that my board requires to me to setup in and out separately? I have an Arduino 101, and I am on Windows 8.1. I do know the button is oriented correctly because I ran the button example.
[code]
/*
  Tell DCS-BIOS to use a serial connection and use interrupt-driven
  communication. The main program will be interrupted to prioritize
  processing incoming data.
  
  This should work on any Arduino that has an ATMega328 controller
  (Uno, Pro Mini, many others).
 */
#define DCSBIOS_DEFAULT_SERIAL

#include "DcsBios.h"
/* paste code snippets from the reference documentation here */
/* Declare a Master Caution Reset button on pin 10 */
/* Make the LED connected to pin 13 into a Master Caution Light */
DcsBios::Switch2Pos masterCautionBtn("UFC_MASTER_CAUTION", 10);
DcsBios::LED mcLed(0x1012, 0x0800, 13);

void setup() {
  DcsBios::setup();
}

void loop() {
  DcsBios::loop();
}

[/code]

**Comment by Mattack-1412** [comment]
I also get the Fast_CWD warning

**Comment by jboecker** [comment]
Make sure that your button is connected between Arduino pin 10 and ground.

The Button example has you connect it to +5V and add an external pull-down resistor, probably because they want the pin to be at a logic high voltage when the button is pressed to avoid confusion. DCS-BIOS enables the Arduino's internal pull-up resistor and expects the button to connect the pin to ground when pressed.

You can ignore the FAST_CWD warning, it's just a complaint that socat cannot figure out how to call some function that is completely unrelated to what we are trying to do.

**Comment by Mattack-1412** [comment]
Sorry, it did not work even when I tried touching the two wires together there was no response.

**Comment by Mattack-1412** [comment]
Could I see a schematic because I'm also new to Arduino, and it is possible that I am not plugging in the right things.

**Comment by Mattack-1412** [comment]
FYI I plugged a wire into 10 and the button and a wire from the button to ground.

**Comment by jboecker** [comment]
I just tested it on an Arduino Nano, the sketch works.

Try running the connect-serial-port script without running DCS. Whenever you push the button, you should see the two messages "UFC_MASTER_CAUTION 1" and "UFC_MASTER_CAUTION 0" appearing in the console window.

If that is the case, the Arduino is doing what it should, and something (probably a firewall or other third-party program) is preventing DCS: World from receiving the message. Check your dcs.log for errors.

**Comment by Mattack-1412** [comment]
It didn't show anything when I tried it and when I disabled the firewall, so I'm going to try to download the libraries and code and stuff again and see if it works otherwise Ill just return the Arduino 101 and buy an Uno.

**Comment by Mattack-1412** [comment]
Thanks for your help. I have tried downloading the files and it didn't change anything so ill come back when I have a different Arduino,

**Comment by Mattack-1412** [comment]
I bought an OSEPP Arduino Mega 2560 R3 Plus and everything works! Great Program!
