### ISSUE TITLE
Huey Caution Light Panel Reset Test

### ISSUE THREAD

**Issue by PrestaMath** [dcs-bios/dcs-bios#88]
Hello and thanks for Dcs-Bios.

I have a minor issue with sending command to operate Dcs Huey switch with
- CLP_RESET_TEST_SW 0\n -> does not react, even with 1 and 2 value
- CLP_BRIGHT_DIM_SW 2\n ->  turn pilot sight into lime green 

And no problem with others switches  like chip detector when sending CHIP_DET_SW 1\n for example.

I am working with
- dcs 1.5.3.xxx
- dcs bios most recent version 
- python 2.7

I work on an android project wich, for the moment implement all switches needed to start engine like entire electric, engine, caution panels. Everything work fine so far, except for the submited issue.

Best regards.

**Comment by jboecker** [comment]
A few device IDs seem to have changed in the Huey. I'll have to do some search and replace in UH1H.lua.

**Comment by PrestaMath** [comment]
In UH1H.lua I found : 
defineRockerSwitch("CLP_RESET_TEST_SW", 16, 3001, 3001, 3001, 3001, 111, "Caution Lights Panel", "Test/Reset Rocker Switch")

In DcsWorld/Mods/aircraft/Uh-1h/input...Saitek X52...lua I found :
{down = 3003, up = 3003, cockpit_device_id = 15, value_down = 1, value_up = 0,  name = _("Caution Panel Test/Reset Switch Reset"),  category = _("Pedestal"), },

Does it help ?

**Comment by PrestaMath** [comment]
Ok good pick, I will try to make a pull request for the fix.
In UH1H.lua file device id must be set to 15 as found in the Belsimtek's SaitekX52...lua file. 
The corrected lines will look likes :

```
defineRockerSwitch("CLP_RESET_TEST_SW", 15, 3001, 3001, 3001, 3001, 111, "Caution Lights Panel", "Test/Reset Rocker Switch")
defineRockerSwitch("CLP_BRIGHT_DIM_SW", 15, 3002, 3002, 3002, 3002, 112, "Caution Lights Panel", "Bright/Dim Rocker Switch")
```
I tested it with my Android App which you can find on dcs forum [here](http://forums.eagle.ru/showthread.php?t=167533)

I also had trouble with chaff counters but that is an other story ;)

Cheers
