### ISSUE TITLE
Potentiometer use causing DCS BIOS to crash

### ISSUE THREAD

**Issue by amyandpeteb** [dcs-bios/dcs-bios#89]
I use the potentiometer in DCS BIOS but after adjusting it a few times, it crashes DCS BIOS. Any suggestions?

**Comment by jboecker** [comment]
Not without knowing your sketch and circuit schematic.
First of all, what do you mean by "crashing DCS-BIOS"?

**Comment by amyandpeteb** [comment]
Thanks for the response.

The circuit matches the one in the DCS BIOS demo.  I can get it to work just fine and it reads out on the MS-DOS (command prompt) screen without any problem.  When playing the game, it will turn the knob I have it assigned to once or twice when I turn it, but after that it stops responding.  When I go back to the Command Prompt screen, it shows a bunch of characters, slashes, etc.  Would it be easier if I try to copy it into the screen?

Here is the sketch.  I am using the latest build (0.5.0 of DCS Bios and version 0.2.3 of the library.

#define DCSBIOS_DEFAULT_SERIAL
#include "DcsBios.h"


/* Set Master Arm switch to Pin 0 and 1 */
DcsBios::Switch3Pos ahcpMasterArm("AHCP_MASTER_ARM", 0, 1);

/* Set GunPac Arm switch to Pin 2 and 3 */
DcsBios::Switch3Pos ahcpGunpac("AHCP_GUNPAC", 2, 3);

/* Set Laser Arm switch to Pin 4 and 5 */
DcsBios::Switch3Pos ahcpLaserArm("AHCP_LASER_ARM", 4, 5);

/* Set TGP switch to Pin 6 */
DcsBios::Switch2Pos ahcpTgp("AHCP_TGP", 6);

/* Set CICU switch to Pin 7 */
DcsBios::Switch2Pos ahcpCicu("AHCP_CICU", 7);

/* Set CICU switch to Pin 8 */
DcsBios::Switch2Pos ahcpJtrs("AHCP_JTRS", 8);

/* Set IFFCC switch to Pin 9 and 10 */
DcsBios::Switch3Pos ahcpIffcc("AHCP_IFFCC", 9, 10);

/* Set Autopilot mode switch to Pin 11 and 12 */
DcsBios::Switch3Pos lasteApMode("LASTE_AP_MODE", 11, 12);

/* Set Autopilot engage / disengage switch to Pin 13 */
DcsBios::Switch2Pos lasteApToggle("LASTE_AP_TOGGLE", 13);

/*this is a test...I'm having problems with the potentiometer and I want to check it out with the ILS volume A0*/
DcsBios::Potentiometer ilsVol("ILS_VOL", A0);







void setup()
{
  DcsBios::setup();

}

void loop()
{
  DcsBios::loop();

}

**Comment by amyandpeteb** [comment]
I figured this out, with the above info.  Thanks!
