### ISSUE TITLE
Speed brakes and wheel brakes in the A10C?

### ISSUE THREAD

**Issue by amyandpeteb** [dcs-bios/dcs-bios#90]
Is there a way of triggering the wheel brakes with a push button or extending / retracting the speed brakes in DCS-BIOS?  Right now I am using keyboard commands from the Leonardo Arduino board and it is very "stuttery" unfortunately, meaning that it isn't smooth like when I have the keyboard connected to the computer.

Thanks!

**Comment by jboecker** [comment]
It's not clickable in the cockpit, so it's not in DCS-BIOS. It may or may not be possible to implement with a look at the joystick binding files, but when impementing the A-10C module I only looked through the clickabledata.lua file.
