### ISSUE TITLE
NTTR longitude always zero degrees

### ISSUE THREAD

**Issue by Reksi-Erkki** [dcs-bios/dcs-bios#91]
The latitude/longitude degrees work fine in the Black Sea area, but longitude is always zero in Nevada - probably because the degrees seem to be a) truncated to 6 bits and b) forced between 0...59. Also, the minutes part is a complement (60 minus actual) of the true position.

Just in case we'll get more maps (on the Southern hemisphere, even) it might be a good idea to allow -90...+90 degrees of latitude and -180...+180 degrees of longitude. Actually, even Normandy is on the Western hemisphere.

The degrees (signed int, instead of unsigned) and minutes would still nicely fit in one 16-bit word each.

**Comment by WarLord211** [comment]
Fixed in flightpanel bios fork 0.7.35
