### ISSUE TITLE
Nothing Happens in cockpit but in DCS BIOS yes...

### ISSUE THREAD

**Issue by Thirtykay** [dcs-bios/dcs-bios#93]
So , here is my problem , i followed the instruction of the user guide on the dcs bios website. Everything sounds to work , but when i open the connect-serial-port.cmd and toggle a switch , dcs-bios detect it but it does nothing in game.

Hoping that you can help me.

Thanks in advance.
![issues](https://cloud.githubusercontent.com/assets/18270037/16710245/1e56b926-4628-11e6-99f1-a87a00b9cbfd.png)

Note : I have a Arduino Uno R3 , using a USB cable for COM , Baudrate is 250000 and COMPORT is 3

**Comment by jboecker** [comment]
The data gets to socat, but not to DCS. Either DCS-BIOS has not been set up correctly so no one is listening (when you have both DCS: World 1.5 and 2.0 installed, you need to set up the Lua part in both Saved Games\DCS and Saved Games\DCS.openalpha), or a firewall or antivirus program is interfering.

If DCS-BIOS is running, it should create a `dcs-bios.log` file next to `dcs.log`. If that does not exist, double check the setup of the Lua part and temporarily disable anything else that uses Export.lua.

Check dcs.log for any errors.

**Comment by Thirtykay** [comment]
Thanks for your answer.

-I tried to disable firewall and Windows Defender , no effect that still not work

-I've tried to set up DCS-BIOS in Dcs.openalpha by copying the script folder of the DCS folder , no effect.

-There's no dcs-bios.log in the logs folder , and there's is error about dcs-bios in the logs.

-And Something i've dont understand , what is the Lua part ? is it the Export.lua that comes with the Dcs-bios-0.5.0 folder ?

Thanks for your answer.

**Comment by jboecker** [comment]
The Lua part refers to the Export.lua and the DCS-BIOS folder that you copy to your %USERPROFILE%\Saved Games\DCS\Scripts folder.

Please post your dcs.log.

**Comment by Thirtykay** [comment]
Dcs.logs link below
http://pastebin.com/wUbtERfu

**Comment by jboecker** [comment]
There are no Lua errors at all in there. If there is no file `C:\Users\Thirtykay\Saved Games\DCS\Logs\dcs-bios.log` but you are using the Export.lua that comes with DCS-BIOS (i.e. there are no other tools that use Export.lua), I am out of ideas. Creating that log file is one of the very first things DCS-BIOS is doing.

It looks like DCS-BIOS is not being executed at all by DCS.

Just to be sure, post your `C:\Users\Thirtykay\Saved Games\DCS\Scripts\Export.lua`.

**Comment by Thirtykay** [comment]
I think i have found a solution , but first , content of the export.

http://pastebin.com/VFWBUPj9

My script folder is not at the good place i think.

C:\Users\Thirtykay\Saved Games\DCS\Scripts\Scripts\Export.lua

**Comment by jboecker** [comment]
That explains it. DCS looks for `Saved Games\DCS\Scripts\Export.lua`, which does not exist and moves on without loading DCS-BIOS.
