### ISSUE TITLE
KA-50 Reset Button and LED not working

### ISSUE THREAD

**Issue by lancer2000** [dcs-bios/dcs-bios#96]
Hi
Targeting mode reset button did not work and LED. I have ready left panel (Targeting Mode Control Panel, R-800, APU Panel...). Other buttons and LEDs works OK.

The situation is strange
If I click this button in game then LED works on my panel and reset targeting mode in game. But if I click this button on my panel then LED did not work, in game button is clicked but not reset targeting mode

**Comment by danieltian** [comment]
I can confirm this issue. It's configured correctly in DCS BIOS, but unlike the other LED push buttons, this one pushes the button down but does not turn on the LED, nor does it reset the targeting system. It merely moves the button up and down, but does not do anything beyond that.

**Comment by danieltian** [comment]
I also checked against some Helios profiles, they all trigger pressing the backspace key instead of using the reset button's export control. It's definitely a bug within DCS.
